// supabase/functions/update_item_status_in_sheet/index.ts
// Updates the "Delivery Status" column of the matching row in the "Spare Part" AppSheet sheet
// when a quotation item's status changes. AppSheet's key column ("ID") is auto-generated by the
// sheet itself (not something we control or send on Add), so the row is located first via a
// Find action matching on "Quotation_item_ID" (the same column write_item_to_sheet populates),
// then edited using the real ID that Find returns.
//
// QNEW-65: the whole Find+Edit sequence is logged as one 'update_status' row in
// qvm_new_apps.appsheet_sync_logs - 'pending' before the sequence starts, then updated with the
// outcome (including a 'row not found' error if Find comes back empty, since the write itself
// never happens in that case).
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const APP_ID = Deno.env.get("APPSHEET_APP_ID")!;
const ACCESS_KEY = Deno.env.get("APPSHEET_ACCESS_KEY")!;
const TABLE_NAME = Deno.env.get("APPSHEET_TABLE_NAME") ?? "Spare Part";

const APPSHEET_BASE = `https://api.appsheet.com/api/v2/apps/${APP_ID}/tables/${encodeURIComponent(TABLE_NAME)}/Action`;

const logsClient = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
).schema("qvm_new_apps");

async function logSyncStart(action: string, sourceTable: string, recordId: number, payload: unknown, createdBy: string | null) {
  const { data } = await logsClient.from("appsheet_sync_logs")
    .insert({ action, source_table: sourceTable, record_id: recordId, payload_sent: payload, created_by: createdBy })
    .select("id")
    .single();
  return data?.id as number | undefined;
}

async function logSyncFinish(id: number | undefined, status: "success" | "error", response: unknown, httpStatus: number | null, errorMessage?: string) {
  if (!id) return;
  await logsClient.from("appsheet_sync_logs")
    .update({ status, appsheet_response: response, http_status: httpStatus, error_message: errorMessage ?? null, responded_at: new Date().toISOString() })
    .eq("id", id);
}

async function appsheetCall(body: Record<string, unknown>) {
  const res = await fetch(APPSHEET_BASE, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ApplicationAccessKey: ACCESS_KEY,
    },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  let json;
  try {
    json = text ? JSON.parse(text) : null;
  } catch {
    json = text;
  }
  if (!res.ok) {
    throw new Error(`AppSheet ${body.Action} failed: ${res.status} ${JSON.stringify(json)}`);
  }
  return json;
}

async function findRowId(quotationItemId: number): Promise<string | null> {
  const result = await appsheetCall({
    Action: "Find",
    Properties: {
      Selector: `Filter("${TABLE_NAME}", [Quotation_item_ID] = "${quotationItemId}")`,
    },
    Rows: [],
  });
  if (Array.isArray(result) && result.length > 0) {
    return result[0]?.ID ?? null;
  }
  return null;
}

// Pulls the HTTP status back out of appsheetCall's "AppSheet Action failed: <status> <body>" error
// message, so failed syncs still populate appsheet_sync_logs.http_status.
function extractHttpStatus(err: unknown): number | null {
  const match = /failed: (\d+)/.exec(String(err));
  return match ? Number(match[1]) : null;
}

serve(async (req) => {
  try {
    const { quotation_item_id, created_by } = await req.json();
    if (!quotation_item_id) {
      return new Response(JSON.stringify({ error: "quotation_item_id required" }), { status: 400 });
    }

    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
    ).schema("qvm_new_apps");

    // Fetch the item's current status
    const { data: item, error: itemErr } = await supabase
      .from("quotation_items")
      .select("quotation_item_id, item_status")
      .eq("quotation_item_id", quotation_item_id)
      .maybeSingle();

    if (itemErr || !item) {
      console.error("Item fetch failed:", itemErr);
      return new Response(JSON.stringify({ error: "Item not found" }), { status: 404 });
    }

    // Resolve the status label from list_data
    let itemStatusName = "";
    if (item.item_status) {
      const { data: statusRow } = await supabase
        .from("list_data")
        .select("list_data")
        .eq("list_data_id", item.item_status)
        .maybeSingle();
      itemStatusName = statusRow?.list_data || "";
    }

    const rowId = await findRowId(quotation_item_id);
    if (!rowId) {
      console.error(`No sheet row found for quotation_item_id ${quotation_item_id}`);
      const logId = await logSyncStart("update_status", "quotation_items", quotation_item_id, null, created_by ?? null);
      await logSyncFinish(logId, "error", null, null, "Row not found in sheet for this item");
      return new Response(JSON.stringify({ error: "Row not found in sheet for this item" }), { status: 404 });
    }

    const editRow = { ID: rowId, "Delivery Status": itemStatusName };
    const logId = await logSyncStart("update_status", "quotation_items", quotation_item_id, editRow, created_by ?? null);

    try {
      const response = await appsheetCall({ Action: "Edit", Properties: {}, Rows: [editRow] });
      await logSyncFinish(logId, "success", response, 200);
    } catch (appsheetErr) {
      await logSyncFinish(logId, "error", null, extractHttpStatus(appsheetErr), String(appsheetErr));
      throw appsheetErr;
    }

    console.log(`Delivery Status updated for quotation_item_id ${quotation_item_id} (row ID ${rowId}): ${itemStatusName}`);
    return new Response(JSON.stringify({ success: true, quotation_item_id, status: itemStatusName }), { status: 200 });
  } catch (err) {
    console.error(err);
    return new Response(JSON.stringify({ error: String(err) }), { status: 500 });
  }
});
