-- Synced from QVM/test branch applied migration history (version 20260326124126, name: qpd668_create_profit_margins_branch)
SET search_path TO qvm_new_apps, public;

-- Create branch overrides table if missing
CREATE TABLE IF NOT EXISTS qvm_new_apps.profit_margins_branch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id INT NOT NULL REFERENCES qvm_new_apps.client_branches(customer_id),
  profit_categories_id INT NOT NULL REFERENCES qvm_new_apps.profit_categories(category_id),
  cost_range_id INT NOT NULL REFERENCES qvm_new_apps.cost_categories(cost_range_id),
  percentage NUMERIC,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_by UUID NULL,
  updated_by UUID NULL
);

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE tablename = 'profit_margins_branch' AND indexname = 'uq_profit_margins_branch'
  ) THEN
    EXECUTE 'CREATE UNIQUE INDEX uq_profit_margins_branch ON qvm_new_apps.profit_margins_branch(branch_id, profit_categories_id, cost_range_id)';
  END IF;
END $$;;
