-- Creating a company no longer fights list_data's identity column.
--
-- The design keeps a company's id identical in client_companies and in list_data, because 62
-- functions still read list 1 and every user_data.user_company already written points at a
-- list_data_id. The first version made the company row first and then inserted its id into
-- list_data — which list_data refuses outright:
--
--   428C9  cannot insert a non-DEFAULT value into column "list_data_id"
--          Column "list_data_id" is an identity column defined as GENERATED ALWAYS.
--
-- Inverting it costs nothing and needs no OVERRIDING SYSTEM VALUE: let list_data mint the id, and
-- have the company adopt it. client_companies.company_id is GENERATED BY DEFAULT, so it accepts one.
-- Its own sequence is nudged past the id afterwards, so a later company that IS left to generate
-- its own cannot collide with an id list_data has already handed out.
--
-- Renaming is fixed at the same time: the mirror row was written once and then never touched again,
-- so a company renamed here kept its old name everywhere list 1 is read.

CREATE OR REPLACE FUNCTION qvm_new_apps.admin_upsert_company(
  p_company_id integer DEFAULT NULL,
  p_names      jsonb   DEFAULT NULL,
  p_cr_number  text    DEFAULT NULL,
  p_vat_number text    DEFAULT NULL,
  p_is_active  boolean DEFAULT true
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'qvm_new_apps', 'public' AS $$
DECLARE
  v_uid uuid := auth.uid();
  v_id integer;
  v_default_name text;
BEGIN
  IF NOT qvm_new_apps.is_qparts_admin(v_uid) THEN
    RETURN jsonb_build_object('success', false, 'error', 'Access denied: Qparts Admin only');
  END IF;
  PERFORM qvm_new_apps.assert_names_valid(p_names);

  v_default_name := (SELECT btrim(n->>'name') FROM jsonb_array_elements(p_names) n
                      WHERE (n->>'language_id')::int = qvm_new_apps.default_language_id() LIMIT 1);

  IF p_company_id IS NULL THEN
    -- list_data first: it owns the number, and the company takes the same one so that both halves
    -- of the platform — the 62 functions still reading list 1, and everything built on
    -- client_companies — mean the same company by the same id.
    INSERT INTO qvm_new_apps.list_data (list_id, list_data)
    VALUES (1, v_default_name)
    RETURNING list_data_id INTO v_id;

    INSERT INTO qvm_new_apps.client_companies (company_id, cr_number, vat_number, is_active, created_by, updated_by)
    VALUES (v_id, p_cr_number, p_vat_number, COALESCE(p_is_active, true), v_uid, v_uid);

    PERFORM setval(pg_get_serial_sequence('qvm_new_apps.client_companies', 'company_id'),
                   GREATEST(v_id, (SELECT COALESCE(max(company_id), 1) FROM qvm_new_apps.client_companies)));
  ELSE
    UPDATE qvm_new_apps.client_companies
    SET cr_number = p_cr_number, vat_number = p_vat_number,
        is_active = COALESCE(p_is_active, is_active), updated_by = v_uid, updated_at = now()
    WHERE company_id = p_company_id
    RETURNING company_id INTO v_id;
    IF v_id IS NULL THEN
      RETURN jsonb_build_object('success', false, 'error', 'Company not found');
    END IF;

    -- Keep the mirror telling the truth. Without this a rename shows here and nowhere else.
    UPDATE qvm_new_apps.list_data
    SET list_data = v_default_name, updated_at = now()
    WHERE list_data_id = v_id AND list_id = 1 AND list_data IS DISTINCT FROM v_default_name;
  END IF;

  INSERT INTO qvm_new_apps.client_companies_descriptions (company_id, language_id, name, created_by, updated_by)
  SELECT v_id, (n->>'language_id')::int, btrim(n->>'name'), v_uid, v_uid
  FROM jsonb_array_elements(p_names) n
  WHERE btrim(COALESCE(n->>'name', '')) <> ''
  ON CONFLICT (company_id, language_id) DO UPDATE
    SET name = EXCLUDED.name, updated_by = EXCLUDED.updated_by, updated_at = now();

  -- A language cleared in the editor is removed rather than left behind as a stale translation.
  DELETE FROM qvm_new_apps.client_companies_descriptions d
   WHERE d.company_id = v_id
     AND d.language_id <> qvm_new_apps.default_language_id()
     AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p_names) n
                      WHERE (n->>'language_id')::int = d.language_id
                        AND btrim(COALESCE(n->>'name', '')) <> '');

  RETURN jsonb_build_object('success', true, 'data', jsonb_build_object('company_id', v_id));
END $$;
