-- Companies, workshops and branches — with every name translatable.
--
-- Three things arrive together because they only make sense together:
--
--   1. `languages` — the set of languages the platform speaks, managed from the admin UI. Adding
--      one is a row, never a migration.
--   2. `client_companies` and `client_workshops` — the two tiers above the branch. Companies stop
--      being list_data rows and become a table of their own, KEEPING THEIR EXISTING IDS so that
--      every user_data.user_company and client_branches.list_data_id already written stays valid.
--   3. `*_descriptions` tables — one row per record per language, carrying the name. A foreign key
--      on language_id makes a mistyped language code unrepresentable, which is the whole reason
--      this is a table and not a jsonb column.
--
-- The branch is untouched as an entity: client_branches.customer_id is foreign-keyed from nine
-- tables and named in 62 functions, and every quotation line ever raised points at it. It gains a
-- parent and a translation table; it does not move.

------------------------------------------------------------------------------ languages

CREATE TABLE IF NOT EXISTS qvm_new_apps.languages (
  language_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code         text    NOT NULL UNIQUE,          -- BCP-47: 'en', 'ar', 'ur'
  english_name text    NOT NULL,
  native_name  text    NOT NULL,
  direction    text    NOT NULL DEFAULT 'ltr' CHECK (direction IN ('ltr', 'rtl')),
  is_active    boolean NOT NULL DEFAULT true,
  is_default   boolean NOT NULL DEFAULT false,
  sort_order   integer NOT NULL DEFAULT 100,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now()
);

-- Exactly one default, and it must stay switched on: it is the fallback every reader lands on.
CREATE UNIQUE INDEX IF NOT EXISTS uq_languages_single_default
  ON qvm_new_apps.languages ((is_default)) WHERE is_default;

INSERT INTO qvm_new_apps.languages (code, english_name, native_name, direction, is_default, sort_order)
VALUES ('en', 'English', 'English',  'ltr', true,  10),
       ('ar', 'Arabic',  'العربية', 'rtl', false, 20)
ON CONFLICT (code) DO NOTHING;

CREATE OR REPLACE FUNCTION qvm_new_apps.default_language_id()
RETURNS integer LANGUAGE sql STABLE SET search_path TO 'qvm_new_apps', 'public' AS $$
  SELECT language_id FROM qvm_new_apps.languages WHERE is_default LIMIT 1;
$$;

-- The reader's language for this request. Set by the API layer the same way the JWT claims are:
--   select set_config('app.lang', 'ar', true);
-- Unset, or set to something unknown, falls back to the default rather than erroring.
CREATE OR REPLACE FUNCTION qvm_new_apps.current_language_id()
RETURNS integer LANGUAGE sql STABLE SET search_path TO 'qvm_new_apps', 'public' AS $$
  SELECT COALESCE(
    (SELECT l.language_id FROM qvm_new_apps.languages l
      WHERE l.is_active AND l.code = NULLIF(current_setting('app.lang', true), '')),
    qvm_new_apps.default_language_id());
$$;

------------------------------------------------------------------------------ companies

CREATE TABLE IF NOT EXISTS qvm_new_apps.client_companies (
  company_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cr_number  text,
  vat_number text,
  is_active  boolean NOT NULL DEFAULT true,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS qvm_new_apps.client_companies_descriptions (
  company_id  integer NOT NULL REFERENCES qvm_new_apps.client_companies(company_id) ON DELETE CASCADE,
  language_id integer NOT NULL REFERENCES qvm_new_apps.languages(language_id),
  name        text    NOT NULL CHECK (btrim(name) <> ''),
  description text,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (company_id, language_id)
);
-- Deliberately not unique: the live data already holds "Qparts" and "qparts" as two separate
-- companies, and refusing that at the database would block the migration to protect against
-- something that is legitimately possible. The admin UI warns on a duplicate name instead.
CREATE INDEX IF NOT EXISTS idx_company_name_per_language
  ON qvm_new_apps.client_companies_descriptions (language_id, lower(name));

-- Seed from the list_data rows that have been standing in for companies, ids and all.
INSERT INTO qvm_new_apps.client_companies (company_id)
SELECT ld.list_data_id FROM qvm_new_apps.list_data ld WHERE ld.list_id = 1
ON CONFLICT (company_id) DO NOTHING;

-- The old column holds one name in whichever language it was typed in. Arabic script lands in the
-- Arabic row, everything else in English; the missing half is filled in from the admin UI.
INSERT INTO qvm_new_apps.client_companies_descriptions (company_id, language_id, name)
SELECT ld.list_data_id,
       (SELECT language_id FROM qvm_new_apps.languages
         WHERE code = CASE WHEN ld.list_data ~ '[؀-ۿ]' THEN 'ar' ELSE 'en' END),
       btrim(ld.list_data)
FROM qvm_new_apps.list_data ld
WHERE ld.list_id = 1 AND btrim(COALESCE(ld.list_data, '')) <> ''
ON CONFLICT (company_id, language_id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('qvm_new_apps.client_companies', 'company_id'),
              GREATEST((SELECT COALESCE(max(company_id), 1) FROM qvm_new_apps.client_companies),
                       (SELECT COALESCE(max(list_data_id), 1) FROM qvm_new_apps.list_data)));

------------------------------------------------------------------------------ workshops

CREATE TABLE IF NOT EXISTS qvm_new_apps.client_workshops (
  workshop_id  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id   integer NOT NULL REFERENCES qvm_new_apps.client_companies(company_id),
  city         text,
  region_id    integer,
  location_lat double precision,
  location_lng double precision,
  is_active    boolean NOT NULL DEFAULT true,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now(),
  -- The target of the composite key that ties a branch's company to its workshop's company.
  UNIQUE (workshop_id, company_id)
);

CREATE TABLE IF NOT EXISTS qvm_new_apps.client_workshops_descriptions (
  workshop_id bigint  NOT NULL,
  company_id  integer NOT NULL,       -- carried so a name can be unique WITHIN its company
  language_id integer NOT NULL REFERENCES qvm_new_apps.languages(language_id),
  name        text    NOT NULL CHECK (btrim(name) <> ''),
  description text,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (workshop_id, language_id),
  FOREIGN KEY (workshop_id, company_id)
    REFERENCES qvm_new_apps.client_workshops (workshop_id, company_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_workshop_name_per_company_language
  ON qvm_new_apps.client_workshops_descriptions (company_id, language_id, lower(name));

------------------------------------------------------------------------------ branches

ALTER TABLE qvm_new_apps.client_branches
  ADD COLUMN IF NOT EXISTS workshop_id bigint REFERENCES qvm_new_apps.client_workshops(workshop_id);
CREATE INDEX IF NOT EXISTS idx_client_branches_workshop ON qvm_new_apps.client_branches (workshop_id);

CREATE TABLE IF NOT EXISTS qvm_new_apps.client_branches_descriptions (
  customer_id integer NOT NULL REFERENCES qvm_new_apps.client_branches(customer_id) ON DELETE CASCADE,
  language_id integer NOT NULL REFERENCES qvm_new_apps.languages(language_id),
  name        text    NOT NULL CHECK (btrim(name) <> ''),
  description text,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (customer_id, language_id)
);

-- Every existing branch becomes a workshop of the same name holding that one branch. On this data
-- the branches ARE the workshops — "PAC", "Body and Paint", "PCVC" are Petromin's workshops, not
-- its addresses — so this backfill states what is already true and leaves the admin to add real
-- branches underneath rather than to untangle a placeholder.
DO $backfill$
DECLARE
  r record;
  v_ws bigint;
  v_lang integer;
BEGIN
  FOR r IN SELECT cb.customer_id, cb.branch_name, cb.list_data_id, cb.city, cb.region_id,
                  cb.location_lat, cb.location_lng
             FROM qvm_new_apps.client_branches cb
            WHERE cb.workshop_id IS NULL
  LOOP
    -- A branch whose company row is missing (deleted list_data) gets one so the tree stays whole.
    INSERT INTO qvm_new_apps.client_companies (company_id) VALUES (r.list_data_id)
    ON CONFLICT (company_id) DO NOTHING;

    INSERT INTO qvm_new_apps.client_workshops (company_id, city, region_id, location_lat, location_lng)
    VALUES (r.list_data_id, r.city, r.region_id, r.location_lat, r.location_lng)
    RETURNING workshop_id INTO v_ws;

    v_lang := (SELECT language_id FROM qvm_new_apps.languages
                WHERE code = CASE WHEN COALESCE(r.branch_name, '') ~ '[؀-ۿ]' THEN 'ar' ELSE 'en' END);

    INSERT INTO qvm_new_apps.client_workshops_descriptions (workshop_id, company_id, language_id, name)
    VALUES (v_ws, r.list_data_id, v_lang, COALESCE(NULLIF(btrim(r.branch_name), ''), 'Workshop ' || v_ws));

    INSERT INTO qvm_new_apps.client_branches_descriptions (customer_id, language_id, name)
    VALUES (r.customer_id, v_lang, COALESCE(NULLIF(btrim(r.branch_name), ''), 'Branch ' || r.customer_id))
    ON CONFLICT (customer_id, language_id) DO NOTHING;

    UPDATE qvm_new_apps.client_branches SET workshop_id = v_ws WHERE customer_id = r.customer_id;
  END LOOP;
END $backfill$;

ALTER TABLE qvm_new_apps.client_branches ALTER COLUMN workshop_id SET NOT NULL;

-- A branch can never hang under a workshop belonging to another company. Enforced, not remembered.
ALTER TABLE qvm_new_apps.client_branches
  DROP CONSTRAINT IF EXISTS client_branches_workshop_company_fk;
ALTER TABLE qvm_new_apps.client_branches
  ADD CONSTRAINT client_branches_workshop_company_fk
  FOREIGN KEY (workshop_id, list_data_id)
  REFERENCES qvm_new_apps.client_workshops (workshop_id, company_id);

------------------------------------------------------------------------------ "no empty workshop"
--
-- No foreign key expresses "a workshop must have branches" — the relationship points the other way.
-- A DEFERRED constraint trigger does: the check runs at COMMIT, so a transaction is free to move
-- the last branch from one workshop to another, or to insert a workshop and its branches in either
-- order, and is only refused if it ENDS with a workshop standing empty.

CREATE OR REPLACE FUNCTION qvm_new_apps.assert_workshop_has_branches()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'qvm_new_apps', 'public' AS $$
DECLARE
  v_ws bigint := COALESCE(NEW.workshop_id, OLD.workshop_id);
  v_n  integer;
BEGIN
  IF v_ws IS NULL THEN RETURN NULL; END IF;
  -- A workshop deleted in the same transaction has nothing left to answer for.
  IF NOT EXISTS (SELECT 1 FROM qvm_new_apps.client_workshops w WHERE w.workshop_id = v_ws) THEN
    RETURN NULL;
  END IF;
  SELECT count(*) INTO v_n FROM qvm_new_apps.client_branches b WHERE b.workshop_id = v_ws;
  IF v_n = 0 THEN
    RAISE EXCEPTION 'Workshop % would be left with no branches. Add a branch, or deactivate the workshop instead.', v_ws
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NULL;
END $$;

-- Insert on the workshop side needs its own shim: NEW there carries workshop_id under a different
-- meaning than on the branch side.
CREATE OR REPLACE FUNCTION qvm_new_apps.assert_workshop_has_branches_after_insert()
RETURNS trigger LANGUAGE plpgsql SET search_path TO 'qvm_new_apps', 'public' AS $$
DECLARE v_n integer;
BEGIN
  SELECT count(*) INTO v_n FROM qvm_new_apps.client_branches b WHERE b.workshop_id = NEW.workshop_id;
  IF v_n = 0 THEN
    RAISE EXCEPTION 'Workshop % was created with no branches. A workshop must be created together with at least one branch.', NEW.workshop_id
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS trg_workshop_needs_branch_ins ON qvm_new_apps.client_workshops;
CREATE CONSTRAINT TRIGGER trg_workshop_needs_branch_ins
  AFTER INSERT ON qvm_new_apps.client_workshops
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
  EXECUTE FUNCTION qvm_new_apps.assert_workshop_has_branches_after_insert();

DROP TRIGGER IF EXISTS trg_workshop_needs_branch_del ON qvm_new_apps.client_branches;
CREATE CONSTRAINT TRIGGER trg_workshop_needs_branch_del
  AFTER DELETE OR UPDATE OF workshop_id ON qvm_new_apps.client_branches
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
  EXECUTE FUNCTION qvm_new_apps.assert_workshop_has_branches();

------------------------------------------------------------------------------ resolved views
--
-- The fallback chain — the reader's language, then the default, then whatever exists — is written
-- ONCE, here. Every RPC selects a plain `name` from these views and never learns about languages.

CREATE OR REPLACE VIEW qvm_new_apps.v_client_companies AS
SELECT c.company_id, c.cr_number, c.vat_number, c.is_active,
       d.name, d.description, d.language_id AS name_language_id
FROM qvm_new_apps.client_companies c
LEFT JOIN LATERAL (
  SELECT d.* FROM qvm_new_apps.client_companies_descriptions d
   WHERE d.company_id = c.company_id
   ORDER BY (d.language_id = qvm_new_apps.current_language_id()) DESC,
            (d.language_id = qvm_new_apps.default_language_id()) DESC,
            d.language_id
   LIMIT 1
) d ON true;

CREATE OR REPLACE VIEW qvm_new_apps.v_client_workshops AS
SELECT w.workshop_id, w.company_id, w.city, w.region_id, w.location_lat, w.location_lng, w.is_active,
       d.name, d.description, d.language_id AS name_language_id,
       (SELECT count(*) FROM qvm_new_apps.client_branches b WHERE b.workshop_id = w.workshop_id) AS branch_count
FROM qvm_new_apps.client_workshops w
LEFT JOIN LATERAL (
  SELECT d.* FROM qvm_new_apps.client_workshops_descriptions d
   WHERE d.workshop_id = w.workshop_id
   ORDER BY (d.language_id = qvm_new_apps.current_language_id()) DESC,
            (d.language_id = qvm_new_apps.default_language_id()) DESC,
            d.language_id
   LIMIT 1
) d ON true;

CREATE OR REPLACE VIEW qvm_new_apps.v_client_branches AS
SELECT b.customer_id, b.workshop_id, b.list_data_id AS company_id, b.city, b.region_id,
       b.location_lat, b.location_lng, b.is_bulk_client, b.order_category, b.zoho_id,
       -- The untranslated column stays the last resort: a branch created before this migration and
       -- never given a description still has a name to show.
       COALESCE(d.name, b.branch_name) AS name,
       d.description, d.language_id AS name_language_id,
       b.branch_name AS legacy_branch_name
FROM qvm_new_apps.client_branches b
LEFT JOIN LATERAL (
  SELECT d.* FROM qvm_new_apps.client_branches_descriptions d
   WHERE d.customer_id = b.customer_id
   ORDER BY (d.language_id = qvm_new_apps.current_language_id()) DESC,
            (d.language_id = qvm_new_apps.default_language_id()) DESC,
            d.language_id
   LIMIT 1
) d ON true;

------------------------------------------------------------------------------ people

-- A workshop user sees every branch of their workshop, including ones added next month.
CREATE TABLE IF NOT EXISTS qvm_new_apps.user_workshops (
  user_id     uuid   NOT NULL REFERENCES qvm_new_apps.user_data(user_id) ON DELETE CASCADE,
  workshop_id bigint NOT NULL REFERENCES qvm_new_apps.client_workshops(workshop_id) ON DELETE CASCADE,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, workshop_id)
);

-- A branch may have several managers; every order raised on the branch is assigned to them.
ALTER TABLE qvm_new_apps.user_branches
  ADD COLUMN IF NOT EXISTS is_manager boolean NOT NULL DEFAULT false;

-- One place that answers "which branches may this user see". The scoping rule is currently copied
-- through a dozen dashboard RPCs; that duplication is how an empty dashboard shipped once already.
-- NULL means unrestricted — an internal user with no assignment sees everything, and returning an
-- empty array here instead would quietly mean "nothing".
CREATE OR REPLACE FUNCTION qvm_new_apps.effective_branch_ids(p_user_id uuid)
RETURNS integer[] LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'qvm_new_apps', 'public' AS $$
DECLARE
  v_type int;
  v_role int;
  v_branch int;
  v_ids integer[];
BEGIN
  SELECT user_type, user_role, user_branch INTO v_type, v_role, v_branch
  FROM qvm_new_apps.user_data WHERE user_id = p_user_id;
  IF v_type IS NULL THEN RETURN ARRAY[]::integer[]; END IF;

  SELECT array_agg(DISTINCT b) INTO v_ids FROM (
    -- branches assigned outright, on either side of the house
    SELECT ub.client_branch_id AS b FROM qvm_new_apps.user_branches ub WHERE ub.user_id = p_user_id
    UNION
    SELECT iub.branch_id FROM qvm_new_apps.internal_user_branches iub WHERE iub.user_id = p_user_id
    UNION
    -- every branch under a workshop the user belongs to
    SELECT cb.customer_id FROM qvm_new_apps.user_workshops uw
      JOIN qvm_new_apps.client_branches cb ON cb.workshop_id = uw.workshop_id
     WHERE uw.user_id = p_user_id
    UNION
    -- the single branch on user_data, still the only scope some accounts have
    SELECT v_branch WHERE v_branch IS NOT NULL
  ) s WHERE b IS NOT NULL;

  IF v_ids IS NULL AND v_type = 185 THEN
    RETURN NULL;              -- internal, unassigned: no restriction
  END IF;
  RETURN COALESCE(v_ids, ARRAY[]::integer[]);
END $$;

GRANT SELECT ON qvm_new_apps.v_client_companies, qvm_new_apps.v_client_workshops,
                qvm_new_apps.v_client_branches, qvm_new_apps.languages TO authenticated;
GRANT EXECUTE ON FUNCTION qvm_new_apps.effective_branch_ids(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION qvm_new_apps.current_language_id() TO authenticated;
GRANT EXECUTE ON FUNCTION qvm_new_apps.default_language_id() TO authenticated;
