-- Synced from QVM/test branch applied migration history (version 20260218111317, name: update_user_names_from_main_branch)
-- Update user_name in user_data table to match the user_name from main branch users_main_data
-- This matches on email addresses with normalization for case and trailing characters

UPDATE qvm_new_apps.user_data 
SET user_name = CASE 
    -- Petromin users
    WHEN email = 'A.abueidhah@petromin.com' THEN 'AbdelAziz abueidhah'
    WHEN email = 'a.abueidhah@petromin.com' THEN 'AbdelAziz abueidhah'
    WHEN email = 'A.almarakshi@petromin.com' THEN 'AbdelAziz Almarakshi'
    WHEN email = 'a.almarakshi@petromin.com' THEN 'AbdelAziz Almarakshi'
    WHEN email = 'abdulkareem.aliakbar@petromin.com' THEN 'ABDUL KARIM ALI'
    WHEN email = 'abdullah.nadeem@petromin.com' THEN 'Abdullah Nadeem'
    WHEN email = 'adham.aldini@petromin.com' THEN 'Adham Aldini'
    WHEN email = 'a.elbedaly@petromin.com' THEN 'Omar Elbedaly'
    WHEN email = 'ahmed.jamali@petromin.com' THEN 'Ahmed Jamali'
    WHEN email = 'ahmed.mohamed@petromin.com' THEN 'Ahmed Mohamed'
    WHEN email = 'ahmed.othman@petromin.com' THEN 'Ahmed Othman'
    WHEN email = 'Ahmed.sayed@petromin.com' THEN 'Ahmed Sayed'
    WHEN email = 'ahmed.sayed@petromin.com' THEN 'Ahmed Sayed'
    WHEN email = 'amer.aljabari@petromin.com' THEN 'Amer Aljabari'
    WHEN email = 'Aminah.alotaibi@petromin.com' THEN 'Aminah Alotaibi'
    WHEN email = 'arman.iqbal@petromin.com' THEN 'Arman Iqbal'
    WHEN email = 'arshad.k@petromin.com' THEN 'Arshad K'
    WHEN email = 'ashwin.kumar@petromin.com' THEN 'Shaik Abdulkader'
    WHEN email = 'atawfik@petromin.com' THEN 'Ahmed Tawfik'
    WHEN email = 'atif.awan@petromin.com' THEN 'ATIF AWAN'
    WHEN email = 'bilal.sheikh@petromin.com' THEN 'Bilal Sheikh'
    WHEN email = 'b.padia@petromin.com' THEN 'Brijesh Padia'
    WHEN email = 'deepak.j@petromin.com' THEN 'Deepak Jha'
    WHEN email = 'Eyad.fahad@petromin.com' THEN 'Eyad Fahad'
    WHEN email = 'faisal.akram@petromin.com' THEN 'Faisal Akram'
    WHEN email = 'f.batayb@petromin.com' THEN 'Fahad'
    WHEN email = 'g.syed@petromin.com' THEN 'Ghazal Syed'
    WHEN email = 'g.thanigaivel@petromin.com' THEN 'Gnanavel Thanigaivel'
    WHEN email = 'gulam.hussain@petromin.com' THEN 'Gulam Hussain'
    WHEN email = 'h.alrahil@petromin.com' THEN 'Hisham Alrahil'
    WHEN email = 'imad.shahzad@petromin.com' THEN 'Imad Shahzad'
    WHEN email = 'immam.alam@petromin.com' THEN 'Immam Alam'
    WHEN email = 'jaifer.ali@petromin.com' THEN 'Jaifer Ali'
    WHEN email = 'Jay.galapon@petromin.com' THEN 'Jay Galapon'
    WHEN email = 'jeffrey.d@petromin.com' THEN 'Jeffrey Dsilva'
    WHEN email = 'j.meeran@petromin.com' THEN 'Jaafar Meeran'
    WHEN email = 'Joud.fakoush@petromin.com' THEN 'Joud Fakoush'
    WHEN email = 'Kalander.mafaz@petromin.com' THEN 'Kalander mafaz'
    WHEN email = 'khalid.babiker@petromin.com' THEN 'khalid Babiker'
    WHEN email = 'Loay.abbas@Petromin.com' THEN 'Loay Abbas'
    WHEN email = 'loay.abbas@petromin.com' THEN 'Loay Abbas'
    WHEN email = 'm.abdulwaheed@petromin.com' THEN 'Mohamed Abdulwaheed'
    WHEN email = 'Mahmoud.goudah@petromin.com' THEN 'Mahmoud Goudah'
    WHEN email = 'mahmoud.z@petromin.com' THEN 'Mahmoud Al-Zaani'
    WHEN email = 'majed.khan@petromin.com' THEN 'Majed Khan'
    WHEN email = 'Majed.sayed@petromin.com' THEN 'Majed Sayed'
    WHEN email = 'majid.bashir@petromin.com' THEN 'MAJID BASHIR'
    WHEN email = 'Malik.azhar@petromin.com' THEN 'Malik Azhar'
    WHEN email = 'm.alkasslab@petromin.com' THEN 'Mossab AlKassab'
    WHEN email = 'm.alnasser@petromin.com' THEN 'Mostafa Al Nasser'
    WHEN email = 'm.aslam@petromin.com' THEN 'Mohammed Batook'
    WHEN email = 'm.bata@petromin.com' THEN 'Mohammed Mostafa'
    WHEN email = 'mchengaruth@petromin.com' THEN 'Mousa Chengaruth'
    WHEN email = 'm.elafany@petromin.com' THEN 'Mohammed Kamal'
    WHEN email = 'm.hindi@petromin.com' THEN 'Mohamed Hindi'
    WHEN email = 'mina.malak@petromin.com' THEN 'Mina Malak'
    WHEN email = 'mirza.kashan@petromin.com' THEN 'Mirza Kashan'
    WHEN email = 'm.najah@petromin.com' THEN 'MOHAMMED NAGAH'
    WHEN email = 'mohammed.halmi@petromin.com' THEN 'Mohammed Halmi'
    WHEN email = 'mohammed.khaleel@petromin.com' THEN 'Mohammed Khaleel'
    WHEN email = 'mohammed.saad@petromin.com' THEN 'Mohammed Saad'
    WHEN email = 'Mohammed.zahid@petromin.com' THEN 'Mohammed Zahid'
    WHEN email = 'M.raoofuddin@petromin.com' THEN 'M raoofuddin'
    WHEN email = 'nawab.zada@petromin.com' THEN 'Nawab Zada'
    WHEN email = 'o.ghonem@petromin.com' THEN 'Osama Ghonem'
    WHEN email = 'pac-aboor@petromin.com' THEN 'Mohamed Zaki'
    WHEN email = 'PAC-Darb@petromin.com' THEN 'Mohamed Saeed'
    WHEN email = 's.alromaih@petromin.com' THEN 'Saud Alromaih'
    WHEN email = 'shohidul.islam@petromin.com' THEN 'Shohidul Islam'
    WHEN email = 's.syagha@petromin.com' THEN 'Samer Syagha'
    WHEN email = 'Wael.ali@petromin.com' THEN 'Wael Ali'
    WHEN email = 'wael.saeed@petromin.com' THEN 'Wael Saeed'
    WHEN email = 'Waleed.abdulghafoor@petromin.com' THEN 'Waleed Abdulghafoor'
    WHEN email = 'zahid.asghar@petromin.com' THEN 'Zahid Asghar'
    WHEN email = 'zahidi.joiya@petromin.com' THEN 'Zahidi Joiya'
    
    -- Saptco users (handle trailing newlines)
    WHEN email = 'abdelkarimam@saptco.com.sa' THEN 'Abdelkarim Mohamed'
    WHEN email = 'abdouof@saptco.com.sa' THEN 'Osama Metwally'
    WHEN email = 'ahmedaha@saptco.com.sa' THEN 'Ahmed Aboud'
    WHEN email = 'aldawoodas@saptco.com.sa' THEN 'Ahmed Aldawood'
    WHEN email = 'aliua@saptco.com.sa' THEN 'Mostafa Ali'
    WHEN email = 'alsaeefat@saptco.com.sa' THEN 'AbdAllah Thabet'
    WHEN email = 'alsenanimn@saptco.com.sa' THEN 'M.N.Alsenani'
    WHEN email = 'Alsheikhmh@saptco.com.sa' THEN 'Mustafa AlSheikh'
    WHEN email = 'banayamanas@saptco.com.sa' THEN 'AbdulBasit'
    WHEN email = 'jamiasdp@saptco.com.sa' THEN 'D. Jamias'
    WHEN email = 'fageeraa@saptco.com.sa' THEN 'Ahmed Fageer'
    
    -- Qparts users
    WHEN email = 'abdualmuneim@qparts.co' THEN 'Abdualmuneim'
    WHEN email = 'abdulrahman@qparts.co' THEN 'اغا'
    WHEN email = 'ahmed.abdullah@qparts.co' THEN 'Ahmed Abdullah'
    WHEN email = 'ahmed.elazab@qparts.co' THEN 'Ahmed Elazab'
    WHEN email = 'alaa.khedr196@gmail.com' THEN 'Alaa Khedr'
    WHEN email = 'alaa.khedr@qparts.co' THEN 'Akram Quraby'
    WHEN email = 'alzain@qparts.co' THEN 'Abdullah Alzain'
    WHEN email = 'amir@qparts.co' THEN 'Mahmoud Amir'
    WHEN email = 'Azza@qparts.co' THEN 'Azza Roshdy'
    WHEN email = 'baraa.badreldin@qparts.co' THEN 'براءة'
    WHEN email = 'duaa.anwar@qparts.co' THEN 'دعاء'
    WHEN email = 'ehab@qparts.co' THEN 'ايهاب'
    WHEN email = 'eman.elsaim@qparts.co' THEN 'ايمان'
    WHEN email = 'eslam@qparts.co' THEN 'Eslam AbdelRahman'
    WHEN email = 'hassan.magdy@qparts.co' THEN 'Hassan Magdy'
    WHEN email = 'mohamed.bilal@qparts.co' THEN 'Mohamed Bilal'
    WHEN email = 'mohamed.salah@qparts.co' THEN 'صلاح'
    WHEN email = 'mohannad@qparts.co' THEN 'Mohannad Al Hassan'
    WHEN email = 'omar.moh@qparts.co' THEN 'Omar Mohamed'
    WHEN email = 'omar@qparts.co' THEN 'Omar AlHarbi'
    WHEN email = 'qparts8@gmail.com' THEN 'Ws-Orders'
    WHEN email = 'razaz@qparts.co' THEN 'Razaz ElFatih'
    WHEN email = 'sara.belal@qparts.co' THEN 'Sara Belal'
    
    -- Other companies
    WHEN email = 'Aliao@almajdouie.com' THEN 'Ahmed Omar'
    WHEN email = 'mahadeer@autolead.sa' THEN 'Mahadeer Samsudeen'
    WHEN email = 'mohammeds@autolead.sa' THEN ''
    WHEN email = 'Mohammed.AlOssaimi@shaheen-alarabia.com' THEN 'Mohammed AlOssaimi'
    WHEN email = 'Mohammed.Ghayasuddin@aljomaihauto.com' THEN 'Mohammed Ghayasuddin'
    WHEN email = 'mohammed.kl@taajeer.com' THEN 'Mohammed Gul'
    WHEN email = 'MW-80101-JCS@joil.com.sa' THEN 'Munsiah Workshop'
    WHEN email = 'nsamat2012@hotmail.com' THEN 'Ahmed Mohammed'
    WHEN email = 'alaa@universalcar-sa.com' THEN 'Alaa'
    WHEN email = 'k.alomiry@universalcar-sa.com' THEN 'Khaled Alomiry'
    WHEN email = 'sales.body@universalcar-sa.com' THEN 'Hussain Khamis'
    WHEN email = 'dreams8cars@gmail.com' THEN 'Omar'
    WHEN email = 'lalshanqiti@tawuniya.com' THEN 'Lamis Alshanqiti'
    WHEN email = 'info@carshubksa.com' THEN 'Hassan Foad Elshaboury'
    WHEN email = 'junaid19655@gmail.com' THEN 'Junaid'
    WHEN email = 'ferasmummar@gmail.com' THEN 'Feras Mummar'
    WHEN email = 'peerkhantaukeerraza@gmail.com' THEN 'Taukeer Raza Peerkhan'
    WHEN email = 'sales@smartoneauto.com' THEN 'Smart One Auto'
    WHEN email = 'pd@alkhadrltd.com' THEN 'Akram Karmeesh'
    WHEN email = 'pm@alkhadrltd.com' THEN 'Ahmad Hassan'
    WHEN email = 'Mohamad.hamdan@limarcenter.com' THEN 'Mohamad Hamdan'
    WHEN email = 'ws.pur@mulhimauto.com' THEN 'Dawood Ahmed'
    WHEN email = 'Turbocare27@gmail.com' THEN 'Mohamed kamal Mohamed'
    WHEN email = 'Workshop@gmail.com' THEN 'Mohamed Sameh'
    WHEN email = 'Tech-dream@hotmail.com' THEN 'Hamdy AlMarakby'
    
    -- Keep existing name if no match found
    ELSE user_name
END;;
