-- Synced from QVM/test branch applied migration history (version 20260218134741, name: update_user_roles_from_main_branch_mapping)
-- Create temporary table with main branch user role data
CREATE TEMP TABLE temp_user_role_mapping (
    pi_email TEXT,
    user_role TEXT,
    company_name TEXT
);

-- Insert data from main branch (manually copied from previous query)
INSERT INTO temp_user_role_mapping (pi_email, user_role, company_name) VALUES
('A.abueidhah@petromin.com', 'Service Advisor', 'Petromin East'),
('A.almarakshi@petromin.com', '-', '-'),
('abdelkarimam@saptco.com.sa', 'Subscriber', 'Saptco'),
('abdouof@saptco.com.sa', 'Subscriber', 'Saptco'),
('abdualmuneim@qparts.co', 'Admin', 'Qparts'),
('abdulkareem.aliakbar@petromin.com', 'Service Advisor', 'Petromin West'),
('abdullah.nadeem@petromin.com', 'Subscriber', 'Petromin - Body & Paint'),
('abdulrahman@qparts.co', 'QP Account Manager', 'Qparts'),
('adham.aldini@petromin.com', 'Service Advisor', 'Petromin West'),
('a.elbedaly@petromin.com', '-', 'Petromin Riyadh'),
('ahmed.abdullah@qparts.co', 'QP Account Manager', 'Qparts'),
('ahmedaha@saptco.com.sa', 'Subscriber', 'Saptco'),
('ahmed.elazab@qparts.co', 'QP Account Manager', 'Qparts'),
('ahmed.jamali@petromin.com', 'Branch Manager', 'Petromin West'),
('ahmed.mohamed@petromin.com', 'Service Advisor', 'Petromin West'),
('ahmed.othman@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('ahmed.sayed@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('alaa.khedr196@gmail.com', 'QP Account Manager', 'Qparts'),
('alaa.khedr@qparts.co', 'QP Account Manager', 'Caraagy West'),
('alaa@universalcar-sa.com', 'Service Manager', 'PIT STOP'),
('aldawoodas@saptco.com.sa', 'Subscriber', 'Saptco'),
('ali.akbar@petromin.com', 'Service Advisor', 'Petromin East'),
('Aliao@almajdouie.com', 'Subscriber', 'Al Majdouie East'),
('aliua@saptco.com.sa', 'Subscriber', 'Saptco'),
('alsaeefat@saptco.com.sa', 'Subscriber', 'Saptco'),
('alsenanimn@saptco.com.sa', 'Subscriber', 'Saptco'),
('Alsheikhmh@saptco.com.sa', 'Subscriber', 'Saptco'),
('alzain@qparts.co', 'QP Account Manager', 'Qparts'),
('amer.aljabari@petromin.com', 'Subscriber', 'Petromin - Body & Paint'),
('Aminah.alotaibi@petromin.com', '-', 'Petromin Riyadh'),
('amir@qparts.co', 'QP Account Manager', 'Qparts'),
('arman.iqbal@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('arshad.k@petromin.com', 'Service Advisor', 'Petromin West'),
('ashwin.kumar@petromin.com', 'Admin', 'Petromin Stock'),
('atawfik@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('atif.awan@petromin.com', 'Branch Manager', 'Petromin East'),
('Azza@qparts.co', 'QP Account Manager', 'Qparts'),
('banayamanas@saptco.com.sa', 'Subscriber', 'Saptco'),
('baraa.badreldin@qparts.co', 'QP Account Manager', 'Qparts'),
('bassam.sakhnini@petromin.com', '', 'Petromin West'),
('bilal.sheikh@petromin.com', 'Service Advisor', 'Petromin - Body & Paint'),
('b.padia@petromin.com', 'Admin', 'Petromin Stock'),
('deepak.j@petromin.com', 'Branch Manager', 'Petromin West'),
('dreams8cars@gmail.com', 'Subscriber', 'Tawuniya'),
('duaa.anwar@qparts.co', 'QP Account Manager', 'Qparts'),
('ehab@qparts.co', 'QP Account Manager', 'Qparts'),
('eman.elsaim@qparts.co', 'QP Account Manager', 'Qparts'),
('eslam@qparts.co', 'Admin', 'Qparts'),
('Eyad.fahad@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('fageeraa@saptco.com.sa', 'Subscriber', 'Saptco'),
('faisal.akram@petromin.com', 'Subscriber', 'Petromin - Body & Paint'),
('f.batayb@petromin.com', 'Service Advisor', 'Petromin West'),
('ferasmummar@gmail.com', 'Service Advisor', 'Petromin West'),
('g.syed@petromin.com', 'Service Advisor', 'Petromin West'),
('g.thanigaivel@petromin.com', 'Admin', 'Petromin Stock'),
('gulam.hussain@petromin.com', 'Admin', 'Petromin Stock'),
('h.alrahil@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('hassan.magdy@qparts.co', 'QP technical Support', 'Qparts'),
('hassan.tariq@petromin.com', 'Branch Manager', 'Petromin West'),
('imad.shahzad@petromin.com', 'Branch Manager', 'Petromin West'),
('immam.alam@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('info@carshubksa.com', 'Branch Manager', 'Carshub'),
('jaifer.ali@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('jamiasdp@saptco.com.sa', 'Subscriber', 'Saptco'),
('Jay.galapon@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('jeffrey.d@petromin.com', 'Subscriber', 'Petromin East'),
('j.meeran@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('Joud.fakoush@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('junaid19655@gmail.com', 'Subscriber', 'Petromin West'),
('Kalander.mafaz@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('k.alomiry@universalcar-sa.com', 'Service Advisor', 'Tawuniya'),
('khalid.babiker@petromin.com', 'Service Advisor', 'Petromin - Body & Paint'),
('LAlshanqiti@tawuniya.com', 'Admin', 'Tawuniya'),
('Loay.abbas@Petromin.com', '-', 'Petromin Riyadh'),
('m.abdulwaheed@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('mahadeer@autolead.sa', 'Admin', 'Al Majdouie Riyadh'),
('Mahmoud.goudah@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('mahmoud.z@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('majed.khan@petromin.com', 'Service Advisor', 'Petromin West'),
('Majed.sayed@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('majid.bashir@petromin.com', 'Service Advisor', 'Petromin East'),
('Malik.azhar@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('m.alkasslab@petromin.com', 'Branch Manager', 'Petromin East'),
('m.alnasser@petromin.com', 'Service Advisor', 'Petromin - Body & Paint'),
('m.aslam@petromin.com', 'Branch Manager', 'Petromin West'),
('m.bata@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('mchengaruth@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
(' m.elafany@petromin.com', 'Branch Manager', 'Petromin West'),
('m.hindi@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('mina.malak@petromin.com', 'Branch Manager', 'Petromin East'),
('mirza.kashan@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('m.najah@petromin.com', 'Branch Manager', 'Petromin West'),
('Mohamad.hamdan@limarcenter.com', 'Branch Manager', 'Limar El-Shams'),
('mohamed.bilal@qparts.co', 'QP Account Manager', 'Qparts'),
('mohamed.salah@qparts.co', 'QP Account Manager', 'Qparts'),
('Mohammed.AlOssaimi@shaheen-alarabia.com', 'Branch Manager', 'Jeri Car Services'),
('Mohammed.Ghayasuddin@aljomaihauto.com', 'Branch Manager', 'AC-DELCO'),
('mohammed.halmi@petromin.com', 'Service Advisor', 'Petromin West'),
('mohammed.khaleel@petromin.com', 'Branch Manager', 'Petromin West'),
('mohammed.kl@taajeer.com', 'Branch Manager', 'Motor Lube'),
('mohammed.saad@petromin.com', 'Service Advisor', 'Petromin West'),
('mohammeds@autolead.sa', 'Subscriber', 'Al Majdouie Riyadh'),
('Mohammed.zahid@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('mohannad@qparts.co', 'QP Account Manager', 'Qparts'),
('M.raoofuddin@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('MW-80101-JCS@joil.com.sa', 'Service Advisor', 'Jeri Car Services'),
('nawab.zada@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('nsamat2012@hotmail.com', 'Subscriber', 'Tawuniya'),
('o.ghonem@petromin.com', 'Branch Manager', 'Petromin West'),
('omar.moh@qparts.co', 'Admin', 'Qparts'),
('omar@qparts.co', 'Admin', 'Qparts'),
('pac-aboor@petromin.com', 'Service Advisor', 'Petromin West'),
('PAC-Darb@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('pd@alkhadrltd.com', 'Branch Manager', 'ALKHADR'),
('Peerkhantaukeerraza@gmail.com', 'Service Advisor', 'Petromin Riyadh'),
('pm@alkhadrltd.com', 'Service Advisor', 'ALKHADR'),
('qparts8@gmail.com', 'Subscriber', 'Qparts'),
('razaz@qparts.co', 'QP Account Manager', 'Qparts'),
('sales.body@universalcar-sa.com', 'Service Advisor', 'Tawuniya'),
('sales@smartoneauto.com', 'Subscriber', 'Smart One Auto'),
('s.alromaih@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('sara.belal@qparts.co', 'QP Account Manager', 'Qparts'),
('shohidul.islam@petromin.com', 'Service Advisor', 'Petromin West'),
('s.syagha@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('Tech-dream@hotmail.com', 'Service Advisor', 'Dream of Tech'),
('Turbocare27@gmail.com', 'Service Advisor', 'Turbo Car Care'),
('Wael.ali@petromin.com', 'Service Advisor', 'Petromin Riyadh'),
('wael.saeed@petromin.com', 'Service Advisor', 'Petromin - Body & Paint'),
('Waleed.abdulghafoor@petromin.com', 'Service Advisor', 'Petromin West'),
('Workshop@gmail.com', 'Service Advisor', 'Dream of Tech'),
('ws.pur@mulhimauto.com', 'Service Advisor', 'AlMulhim'),
('zahid.asghar@petromin.com', 'Branch Manager', 'Petromin Riyadh'),
('zahidi.joiya@petromin.com', 'Branch Manager', 'Petromin West');

-- Update user_role based on mapping from main branch
UPDATE qvm_new_apps.user_data ud
SET user_role = CASE
    -- Service Advisor -> 171
    WHEN m.user_role = 'Service Advisor' THEN 171
    -- Branch Manager -> 195
    WHEN m.user_role = 'Branch Manager' THEN 195
    -- Admin and Qparts -> 172
    WHEN m.user_role = 'Admin' AND m.company_name = 'Qparts' THEN 172
    -- Admin and NOT Qparts -> 170
    WHEN m.user_role = 'Admin' AND m.company_name <> 'Qparts' THEN 170
    -- QP Account Manager -> 173
    WHEN m.user_role = 'QP Account Manager' THEN 173
    -- Keep existing role for others
    ELSE ud.user_role
END
FROM temp_user_role_mapping m
WHERE LOWER(TRIM(ud.email)) = LOWER(TRIM(m.pi_email));

-- Drop temporary table
DROP TABLE temp_user_role_mapping;;
