-- Recovered from the QVM/dev branch database's own migration history.
-- Applied through the Supabase dashboard and recorded in
-- supabase_migrations.schema_migrations, but never committed as a file, which is what
-- made branch deploys fail with "Remote migration versions not found in local
-- migrations directory". Body is verbatim from that table's `statements` column.

-- QNEW-8: vendor file attachments + price_source tracking on vendor items.
-- Matches the team's existing model: no RLS, broad anon/authenticated grants, app-layer control.

-- 1) price_source on quotation_vendor_items: 'ai_extracted' | 'manual' (NULL = legacy/unknown).
ALTER TABLE qvm_new_apps.quotation_vendor_items
  ADD COLUMN IF NOT EXISTS price_source text;

-- 2) quotation_attachments: files a vendor (or admin on their behalf) uploads for a quotation.
CREATE TABLE IF NOT EXISTS qvm_new_apps.quotation_attachments (
  attachment_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id        integer NOT NULL,
  vendor_id           integer,
  quotation_vendor_id bigint,
  file_url            text NOT NULL,
  file_path           text,
  file_name           text,
  file_type           text,            -- image | pdf | excel | doc
  mime_type           text,
  file_size           bigint,
  ai_extracted        boolean NOT NULL DEFAULT false,
  created_at          timestamptz NOT NULL DEFAULT now(),
  created_by          uuid DEFAULT auth.uid()
);

CREATE INDEX IF NOT EXISTS idx_quotation_attachments_quotation ON qvm_new_apps.quotation_attachments (quotation_id);
CREATE INDEX IF NOT EXISTS idx_quotation_attachments_qvendor   ON qvm_new_apps.quotation_attachments (quotation_vendor_id);
CREATE INDEX IF NOT EXISTS idx_quotation_attachments_vendor    ON qvm_new_apps.quotation_attachments (vendor_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON qvm_new_apps.quotation_attachments TO anon, authenticated;

-- 3) extend the bulk price-save RPC to also persist price_source when provided.
CREATE OR REPLACE FUNCTION qvm_new_apps.update_quotation_vendor_items_bulk(p_items jsonb)
 RETURNS jsonb
 LANGUAGE plpgsql
AS $function$
DECLARE
  updated jsonb;
  not_found jsonb;
BEGIN
  WITH changes AS (
    SELECT
      (x->>'cost_id')::int                                      AS cost_id,
      x->>'alternative_part_number'                             AS alternative_part_number,
      NULLIF(x->>'available_brand_class','')::int               AS available_brand_class,
      NULLIF(x->>'available_quantity','')::int                  AS available_quantity,
      NULLIF(x->>'cost','')::numeric                            AS cost,
      NULLIF(x->>'sla','')                                      AS sla,
      NULLIF(x->>'discount_percent','')::numeric               AS discount_percent,
      NULLIF(x->>'agency_price','')::numeric                   AS agency_price,
      NULLIF(x->>'vendor_item_status','') ::int                AS vendor_item_status,
      NULLIF(x->>'price_source','')                            AS price_source
    FROM jsonb_array_elements(p_items) AS x
  ),
  upd AS (
    UPDATE qvm_new_apps.quotation_vendor_items qvi
    SET
      alternative_part_number = COALESCE(c.alternative_part_number, qvi.alternative_part_number),
      available_brand_class   = COALESCE(c.available_brand_class, qvi.available_brand_class),
      available_quantity      = COALESCE(c.available_quantity, qvi.available_quantity),
      cost                    = COALESCE(c.cost, qvi.cost),
      sla                     = COALESCE(c.sla, qvi.sla),
      discount_percent        = COALESCE(c.discount_percent, qvi.discount_percent),
      agency_price            = COALESCE(c.agency_price, qvi.agency_price),
      vendor_item_status      = COALESCE(c.vendor_item_status, qvi.vendor_item_status),
      price_source            = COALESCE(c.price_source, qvi.price_source),
      best_cost               = FALSE,
      updated_at              = NOW()
    FROM changes c
    WHERE qvi.cost_id = c.cost_id
    RETURNING qvi.cost_id,
              qvi.alternative_part_number,
              qvi.available_brand_class,
              qvi.available_quantity,
              qvi.cost,
              qvi.sla,
              qvi.discount_percent,
              qvi.agency_price,
              qvi.vendor_item_status,
              qvi.price_source,
              qvi.best_cost
  )
  SELECT COALESCE(jsonb_agg(to_jsonb(upd.*)), '[]'::jsonb)
  INTO updated
  FROM upd;

  SELECT COALESCE(jsonb_agg(to_jsonb(c.*)), '[]'::jsonb)
  INTO not_found
  FROM (
    SELECT
      (x->>'cost_id')::int AS cost_id
    FROM jsonb_array_elements(p_items) AS x
    WHERE NOT EXISTS (
      SELECT 1 FROM qvm_new_apps.quotation_vendor_items q
      WHERE q.cost_id = (x->>'cost_id')::int
    )
  ) AS c;

  RETURN jsonb_build_object(
    'status', true,
    'message', 'Bulk update completed',
    'updated_count', COALESCE(jsonb_array_length(updated), 0),
    'updated', updated,
    'not_found', not_found
  );
END;
$function$;
