-- The cities of Saudi Arabia, and the branch that sits in one.
--
-- Branches carried a free-text `city`, which is how "Riyadh", "riyadh" and "الرياض" become three
-- places. A city is a real thing with a real position, so it gets a table: a foreign key on the
-- branch, coordinates for mapping, and its names in every language the platform speaks — the same
-- description-table pattern as companies, workshops and branches, so a third language reaches
-- cities on the day it is added and not a migration later.
--
-- The 13 administrative regions come with it. list_data list 2 already holds "region", but that is
-- a commercial grouping — West, East, Riyadh, Central — used for account-manager coverage. An
-- administrative region is a different fact about a different thing, so it lives in its own table
-- and client_branches.region_id is left exactly as it was.
--
-- Coordinates are city-centre points, good enough to place a pin and to group branches on a map.
-- They are not survey-grade and are not a substitute for the branch's own lat/lng, which stays.

------------------------------------------------------------------------------ regions

CREATE TABLE IF NOT EXISTS qvm_new_apps.regions (
  region_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_code text    NOT NULL UNIQUE,
  country_code text   NOT NULL DEFAULT 'SA',
  is_active   boolean NOT NULL DEFAULT true,
  sort_order  integer NOT NULL DEFAULT 100,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS qvm_new_apps.regions_descriptions (
  region_id   integer NOT NULL REFERENCES qvm_new_apps.regions(region_id) ON DELETE CASCADE,
  language_id integer NOT NULL REFERENCES qvm_new_apps.languages(language_id),
  name        text    NOT NULL CHECK (btrim(name) <> ''),
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (region_id, language_id)
);

------------------------------------------------------------------------------ cities

CREATE TABLE IF NOT EXISTS qvm_new_apps.cities (
  city_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id    integer NOT NULL REFERENCES qvm_new_apps.regions(region_id),
  location_lat double precision,
  location_lng double precision,
  is_active    boolean NOT NULL DEFAULT true,
  sort_order   integer NOT NULL DEFAULT 100,
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cities_lat_range CHECK (location_lat IS NULL OR location_lat BETWEEN -90 AND 90),
  CONSTRAINT cities_lng_range CHECK (location_lng IS NULL OR location_lng BETWEEN -180 AND 180)
);
CREATE INDEX IF NOT EXISTS idx_cities_region ON qvm_new_apps.cities (region_id);

CREATE TABLE IF NOT EXISTS qvm_new_apps.cities_descriptions (
  city_id     integer NOT NULL REFERENCES qvm_new_apps.cities(city_id) ON DELETE CASCADE,
  language_id integer NOT NULL REFERENCES qvm_new_apps.languages(language_id),
  name        text    NOT NULL CHECK (btrim(name) <> ''),
  created_by uuid, created_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid, updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (city_id, language_id)
);
-- Two cities may share a name across regions — Badr in Madinah and Badr Al Janub in Najran are
-- different places — so the name is held unique within its region, not nationally.
CREATE UNIQUE INDEX IF NOT EXISTS uq_city_name_per_region_language
  ON qvm_new_apps.cities_descriptions (language_id, lower(name));

------------------------------------------------------------------------------ the data

INSERT INTO qvm_new_apps.regions (region_code, sort_order)
SELECT v.code, v.so
FROM (VALUES
  ('riyadh', 'Riyadh', 'منطقة الرياض', 10),
  ('makkah', 'Makkah', 'منطقة مكة المكرمة', 20),
  ('madinah', 'Madinah', 'منطقة المدينة المنورة', 30),
  ('qassim', 'Qassim', 'منطقة القصيم', 40),
  ('eastern', 'Eastern Province', 'المنطقة الشرقية', 50),
  ('asir', 'Asir', 'منطقة عسير', 60),
  ('tabuk', 'Tabuk', 'منطقة تبوك', 70),
  ('hail', 'Hail', 'منطقة حائل', 80),
  ('northern', 'Northern Borders', 'منطقة الحدود الشمالية', 90),
  ('jazan', 'Jazan', 'منطقة جازان', 100),
  ('najran', 'Najran', 'منطقة نجران', 110),
  ('bahah', 'Al Bahah', 'منطقة الباحة', 120),
  ('jouf', 'Al Jouf', 'منطقة الجوف', 130)
) AS v(code, en, ar, so)
ON CONFLICT (region_code) DO NOTHING;

-- Separate statement on purpose: a CTE reading qvm_new_apps.regions cannot see rows another CTE is
-- inserting in the same statement — they share one snapshot — so folding these together silently
-- inserted no names at all.
INSERT INTO qvm_new_apps.regions_descriptions (region_id, language_id, name)
SELECT r.region_id, l.language_id, CASE l.code WHEN 'ar' THEN v.ar ELSE v.en END
FROM (VALUES
  ('riyadh', 'Riyadh', 'منطقة الرياض', 10),
  ('makkah', 'Makkah', 'منطقة مكة المكرمة', 20),
  ('madinah', 'Madinah', 'منطقة المدينة المنورة', 30),
  ('qassim', 'Qassim', 'منطقة القصيم', 40),
  ('eastern', 'Eastern Province', 'المنطقة الشرقية', 50),
  ('asir', 'Asir', 'منطقة عسير', 60),
  ('tabuk', 'Tabuk', 'منطقة تبوك', 70),
  ('hail', 'Hail', 'منطقة حائل', 80),
  ('northern', 'Northern Borders', 'منطقة الحدود الشمالية', 90),
  ('jazan', 'Jazan', 'منطقة جازان', 100),
  ('najran', 'Najran', 'منطقة نجران', 110),
  ('bahah', 'Al Bahah', 'منطقة الباحة', 120),
  ('jouf', 'Al Jouf', 'منطقة الجوف', 130)
) AS v(code, en, ar, so)
JOIN qvm_new_apps.regions r ON r.region_code = v.code
JOIN qvm_new_apps.languages l ON l.code IN ('en', 'ar')
ON CONFLICT (region_id, language_id) DO NOTHING;

WITH c(region_code, en, ar, lat, lng) AS (VALUES
  ('riyadh', 'Riyadh', 'الرياض', 24.7136, 46.6753),
  ('riyadh', 'Diriyah', 'الدرعية', 24.737, 46.576),
  ('riyadh', 'Al Kharj', 'الخرج', 24.1483, 47.305),
  ('riyadh', 'Al Majmaah', 'المجمعة', 25.9039, 45.345),
  ('riyadh', 'Al Zulfi', 'الزلفي', 26.2994, 44.8145),
  ('riyadh', 'Al Quwayiyah', 'القويعية', 24.0716, 45.28),
  ('riyadh', 'Al Dawadmi', 'الدوادمي', 24.5069, 44.3928),
  ('riyadh', 'Wadi ad-Dawasir', 'وادي الدواسر', 20.4667, 44.8),
  ('riyadh', 'Afif', 'عفيف', 23.9065, 42.917),
  ('riyadh', 'Shaqra', 'شقراء', 25.245, 45.25),
  ('riyadh', 'Al Muzahimiyah', 'المزاحمية', 24.4667, 46.2667),
  ('riyadh', 'Hotat Bani Tamim', 'حوطة بني تميم', 23.5167, 46.85),
  ('riyadh', 'Layla', 'ليلى', 22.2833, 46.7333),
  ('riyadh', 'Huraymila', 'حريملاء', 25.1447, 46.1078),
  ('riyadh', 'Thadiq', 'ثادق', 25.2939, 45.86),
  ('riyadh', 'Al Ghat', 'الغاط', 26.0281, 44.9575),
  ('riyadh', 'Marat', 'مرات', 25.0736, 45.4522),
  ('riyadh', 'Rumah', 'رماح', 25.5667, 47.15),
  ('riyadh', 'Al Hariq', 'الحريق', 23.6167, 46.55),
  ('makkah', 'Makkah', 'مكة المكرمة', 21.3891, 39.8579),
  ('makkah', 'Jeddah', 'جدة', 21.4858, 39.1925),
  ('makkah', 'Taif', 'الطائف', 21.2703, 40.4158),
  ('makkah', 'Rabigh', 'رابغ', 22.7986, 39.0349),
  ('makkah', 'Al Qunfudhah', 'القنفذة', 19.1264, 41.0789),
  ('makkah', 'Al Lith', 'الليث', 20.15, 40.2667),
  ('makkah', 'Khulais', 'خليص', 22.15, 39.3167),
  ('makkah', 'Al Jumum', 'الجموم', 21.6167, 39.7),
  ('makkah', 'Turbah', 'تربة', 21.2167, 41.6333),
  ('makkah', 'Ranyah', 'رنية', 21.2667, 42.85),
  ('makkah', 'Al Kamil', 'الكامل', 22.2167, 39.95),
  ('makkah', 'Adham', 'أضم', 20.6167, 40.9333),
  ('makkah', 'Bahrah', 'بحرة', 21.4, 39.4),
  ('makkah', 'King Abdullah Economic City', 'مدينة الملك عبدالله الاقتصادية', 22.4167, 39.1),
  ('madinah', 'Madinah', 'المدينة المنورة', 24.5247, 39.5692),
  ('madinah', 'Yanbu', 'ينبع', 24.0895, 38.0637),
  ('madinah', 'Al Ula', 'العلا', 26.6167, 37.9167),
  ('madinah', 'Badr', 'بدر', 23.7833, 38.7833),
  ('madinah', 'Khaybar', 'خيبر', 25.6944, 39.2917),
  ('madinah', 'Mahd adh Dhahab', 'مهد الذهب', 23.4833, 40.85),
  ('madinah', 'Al Hinakiyah', 'الحناكية', 24.9167, 40.5167),
  ('qassim', 'Buraydah', 'بريدة', 26.326, 43.975),
  ('qassim', 'Unayzah', 'عنيزة', 26.0843, 43.9935),
  ('qassim', 'Ar Rass', 'الرس', 25.8667, 43.5),
  ('qassim', 'Al Bukayriyah', 'البكيرية', 26.1389, 43.6547),
  ('qassim', 'Al Mithnab', 'المذنب', 25.8667, 44.2167),
  ('qassim', 'Riyadh Al Khabra', 'رياض الخبراء', 26.05, 43.5333),
  ('qassim', 'Al Badayea', 'البدائع', 26.0333, 43.7167),
  ('qassim', 'Uyun AlJiwa', 'عيون الجواء', 26.5, 43.7),
  ('eastern', 'Dammam', 'الدمام', 26.4207, 50.0888),
  ('eastern', 'Al Khobar', 'الخبر', 26.2794, 50.2083),
  ('eastern', 'Dhahran', 'الظهران', 26.2361, 50.0393),
  ('eastern', 'Jubail', 'الجبيل', 27.0046, 49.6458),
  ('eastern', 'Al Hofuf', 'الهفوف', 25.3833, 49.5833),
  ('eastern', 'Al Mubarraz', 'المبرز', 25.4167, 49.5667),
  ('eastern', 'Qatif', 'القطيف', 26.5196, 49.9962),
  ('eastern', 'Ras Tanura', 'رأس تنورة', 26.7, 50.0333),
  ('eastern', 'Abqaiq', 'بقيق', 25.9333, 49.6667),
  ('eastern', 'Hafar Al Batin', 'حفر الباطن', 28.4342, 45.9636),
  ('eastern', 'Al Khafji', 'الخفجي', 28.4167, 48.5),
  ('eastern', 'An Nairyah', 'النعيرية', 27.4833, 48.4833),
  ('eastern', 'Safwa', 'صفوى', 26.65, 49.95),
  ('eastern', 'Saihat', 'سيهات', 26.4667, 50.0333),
  ('eastern', 'Qaryat Al Ulya', 'قرية العليا', 27.5667, 47.6833),
  ('asir', 'Abha', 'أبها', 18.2164, 42.5053),
  ('asir', 'Khamis Mushait', 'خميس مشيط', 18.3, 42.7333),
  ('asir', 'Bisha', 'بيشة', 19.9767, 42.6008),
  ('asir', 'Mahayil Asir', 'محايل عسير', 18.55, 42.05),
  ('asir', 'Sarat Abidah', 'سراة عبيدة', 18.2167, 42.8167),
  ('asir', 'An Namas', 'النماص', 19.15, 42.1167),
  ('asir', 'Ahad Rafidah', 'أحد رفيدة', 18.1833, 42.85),
  ('asir', 'Rijal Almaa', 'رجال ألمع', 18.1833, 42.2833),
  ('asir', 'Tathlith', 'تثليث', 19.55, 43.5167),
  ('tabuk', 'Tabuk', 'تبوك', 28.3835, 36.5662),
  ('tabuk', 'Duba', 'ضباء', 27.3493, 35.6961),
  ('tabuk', 'Umluj', 'أملج', 25.0213, 37.2685),
  ('tabuk', 'Haql', 'حقل', 29.2833, 34.9333),
  ('tabuk', 'Al Wajh', 'الوجه', 26.2394, 36.4636),
  ('tabuk', 'Tayma', 'تيماء', 27.6333, 38.55),
  ('tabuk', 'NEOM', 'نيوم', 28.0, 35.3),
  ('hail', 'Hail', 'حائل', 27.5114, 41.7208),
  ('hail', 'Baqaa', 'بقعاء', 27.8833, 42.95),
  ('hail', 'Al Ghazalah', 'الغزالة', 26.8833, 41.3167),
  ('hail', 'Al Shinan', 'الشنان', 27.15, 42.45),
  ('hail', 'Mawqaq', 'موقق', 27.4667, 41.05),
  ('northern', 'Arar', 'عرعر', 30.9753, 41.0381),
  ('northern', 'Rafha', 'رفحاء', 29.6202, 43.499),
  ('northern', 'Turaif', 'طريف', 31.6725, 38.6637),
  ('northern', 'Al Uwayqilah', 'العويقيلة', 30.3333, 42.25),
  ('jazan', 'Jazan', 'جازان', 16.8892, 42.5511),
  ('jazan', 'Sabya', 'صبيا', 17.1494, 42.6256),
  ('jazan', 'Abu Arish', 'أبو عريش', 16.9689, 42.832),
  ('jazan', 'Samtah', 'صامطة', 16.5978, 42.9433),
  ('jazan', 'Ahad Al Masarihah', 'أحد المسارحة', 16.7092, 42.9531),
  ('jazan', 'Farasan', 'فرسان', 16.7, 42.1167),
  ('jazan', 'Al Darb', 'الدرب', 17.7167, 42.25),
  ('jazan', 'Baish', 'بيش', 17.3833, 42.55),
  ('najran', 'Najran', 'نجران', 17.4917, 44.1322),
  ('najran', 'Sharurah', 'شرورة', 17.4833, 47.1167),
  ('najran', 'Habuna', 'حبونا', 17.95, 44.3167),
  ('najran', 'Badr Al Janub', 'بدر الجنوب', 17.9667, 45.0333),
  ('najran', 'Yadamah', 'يدمة', 17.4, 45.2333),
  ('bahah', 'Al Bahah', 'الباحة', 20.0129, 41.4677),
  ('bahah', 'Baljurashi', 'بلجرشي', 19.8594, 41.5644),
  ('bahah', 'Al Mandaq', 'المندق', 20.1667, 41.2833),
  ('bahah', 'Al Aqiq', 'العقيق', 20.2667, 41.65),
  ('bahah', 'Qilwah', 'قلوة', 19.85, 41.3),
  ('jouf', 'Sakaka', 'سكاكا', 29.9697, 40.2064),
  ('jouf', 'Dumat Al Jandal', 'دومة الجندل', 29.8117, 39.8667),
  ('jouf', 'Qurayyat', 'القريات', 31.3333, 37.3333),
  ('jouf', 'Tabarjal', 'طبرجل', 30.5, 38.2167)
), ins AS (
  INSERT INTO qvm_new_apps.cities (region_id, location_lat, location_lng)
  SELECT rg.region_id, c.lat, c.lng
  FROM c JOIN qvm_new_apps.regions rg ON rg.region_code = c.region_code
  -- Re-running the migration must not double the list; the English name is the natural key here.
  WHERE NOT EXISTS (SELECT 1 FROM qvm_new_apps.cities_descriptions d
                     JOIN qvm_new_apps.languages l ON l.language_id = d.language_id
                    WHERE l.code = 'en' AND lower(d.name) = lower(c.en))
  RETURNING city_id, location_lat, location_lng
)
INSERT INTO qvm_new_apps.cities_descriptions (city_id, language_id, name)
SELECT i.city_id, l.language_id, CASE l.code WHEN 'ar' THEN c.ar ELSE c.en END
FROM ins i
JOIN c ON c.lat = i.location_lat AND c.lng = i.location_lng
JOIN qvm_new_apps.languages l ON l.code IN ('en', 'ar')
ON CONFLICT (city_id, language_id) DO NOTHING;

------------------------------------------------------------------------------ the branch's city

ALTER TABLE qvm_new_apps.client_branches
  ADD COLUMN IF NOT EXISTS city_id integer REFERENCES qvm_new_apps.cities(city_id);
CREATE INDEX IF NOT EXISTS idx_client_branches_city ON qvm_new_apps.client_branches (city_id);

ALTER TABLE qvm_new_apps.client_workshops
  ADD COLUMN IF NOT EXISTS city_id integer REFERENCES qvm_new_apps.cities(city_id);

-- Match what is already typed, in either language, and leave the free-text column alone: it is the
-- record of what someone wrote, and the rows that fail to match are exactly the ones worth seeing.
UPDATE qvm_new_apps.client_branches b
SET city_id = m.city_id
FROM (SELECT d.city_id, lower(btrim(d.name)) AS name FROM qvm_new_apps.cities_descriptions d) m
WHERE b.city_id IS NULL AND lower(btrim(COALESCE(b.city, ''))) = m.name;

UPDATE qvm_new_apps.client_workshops w
SET city_id = m.city_id
FROM (SELECT d.city_id, lower(btrim(d.name)) AS name FROM qvm_new_apps.cities_descriptions d) m
WHERE w.city_id IS NULL AND lower(btrim(COALESCE(w.city, ''))) = m.name;

------------------------------------------------------------------------------ resolved views

CREATE OR REPLACE VIEW qvm_new_apps.v_regions AS
SELECT r.region_id, r.region_code, r.country_code, r.is_active, r.sort_order,
       d.name, d.language_id AS name_language_id
FROM qvm_new_apps.regions r
LEFT JOIN LATERAL (
  SELECT d.* FROM qvm_new_apps.regions_descriptions d
   WHERE d.region_id = r.region_id
   ORDER BY (d.language_id = qvm_new_apps.current_language_id()) DESC,
            (d.language_id = qvm_new_apps.default_language_id()) DESC, d.language_id
   LIMIT 1
) d ON true;

CREATE OR REPLACE VIEW qvm_new_apps.v_cities AS
SELECT c.city_id, c.region_id, c.location_lat, c.location_lng, c.is_active, c.sort_order,
       d.name, d.language_id AS name_language_id,
       vr.name AS region_name, vr.region_code
FROM qvm_new_apps.cities c
JOIN qvm_new_apps.v_regions vr ON vr.region_id = c.region_id
LEFT JOIN LATERAL (
  SELECT d.* FROM qvm_new_apps.cities_descriptions d
   WHERE d.city_id = c.city_id
   ORDER BY (d.language_id = qvm_new_apps.current_language_id()) DESC,
            (d.language_id = qvm_new_apps.default_language_id()) DESC, d.language_id
   LIMIT 1
) d ON true;

GRANT SELECT ON qvm_new_apps.v_cities, qvm_new_apps.v_regions TO authenticated;

------------------------------------------------------------------------------ readable by the app

-- Every signed-in user needs the city list: it fills the pickers on the branch and workshop forms.
CREATE OR REPLACE FUNCTION public.list_cities() RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO '' AS $$
  SELECT jsonb_build_object('success', true, 'data', COALESCE((
    SELECT jsonb_agg(jsonb_build_object(
             'city_id', c.city_id, 'name', c.name,
             'region_id', c.region_id, 'region_name', c.region_name, 'region_code', c.region_code,
             'location_lat', c.location_lat, 'location_lng', c.location_lng)
           ORDER BY c.region_code, c.name)
      FROM qvm_new_apps.v_cities c WHERE c.is_active), '[]'::jsonb));
$$;

GRANT EXECUTE ON FUNCTION public.list_cities() TO authenticated;
