-- Update user_branch mappings based on actual data from main branch
-- This maps branch names to customer IDs from the clients_branches table structure

-- Create a mapping table for branches based on the clients_branches structure
WITH branch_mappings AS (
    SELECT
        'Aboor' as branch_name, 13 as customer_id, 'Petromin Stock' as company
    UNION ALL SELECT 'AlAmal', 3, 'Petromin Stock'
    UNION ALL SELECT 'Al-DahamLand', 10, 'Petromin Stock'
    UNION ALL SELECT 'AL Jabria Centre', 16, 'Petromin Stock'
    UNION ALL SELECT 'Al Murabaland', 17, 'Petromin Stock'
    UNION ALL SELECT 'Al-Safa Land', 38, 'Petromin Stock'
    UNION ALL SELECT 'Al Taj', 5, 'Petromin Stock'
    UNION ALL SELECT 'Hamdaniya', 12, 'Petromin Stock'
    UNION ALL SELECT 'Madinah Arbaeen.', 4, 'Petromin Stock'
    UNION ALL SELECT 'Nahada', 7, 'Petromin Stock'
    UNION ALL SELECT 'Rabea', 1, 'Petromin Stock'
    UNION ALL SELECT 'Al Duwadimi', 24, 'Petromin Stock'
    UNION ALL SELECT 'Alkahrj', 10, 'Petromin Riyadh'
    UNION ALL SELECT 'Al-Malaz', 4, 'Petromin Riyadh'
    UNION ALL SELECT 'AlQassim', 13, 'Petromin Riyadh'
    UNION ALL SELECT 'AlQassim Buraidah', 14, 'Petromin Riyadh'
    UNION ALL SELECT 'Azizia', 3, 'Petromin Riyadh'
    UNION ALL SELECT 'Badiya', 7, 'Petromin Riyadh'
    UNION ALL SELECT 'Darb', 11, 'Petromin Riyadh'
    UNION ALL SELECT 'Exit 13.', 6, 'Petromin Riyadh'
    UNION ALL SELECT 'Exit 14.', 8, 'Petromin Riyadh'
    UNION ALL SELECT 'Khurais', 5, 'Petromin Riyadh'
    UNION ALL SELECT 'Masif', 1, 'Petromin Riyadh'
    UNION ALL SELECT 'Thumama', 2, 'Petromin Riyadh'
    UNION ALL SELECT 'Jalawia/DAMMAM', 3, 'Petromin East'
    UNION ALL SELECT 'Rashid mall/KHOBAR', 1, 'Petromin East'
    UNION ALL SELECT 'Rayan/DAMMAM', 2, 'Petromin East'
    UNION ALL SELECT 'Hassa - Tahsilat Al Shaqeeq', 4, 'Petromin East'
    UNION ALL SELECT 'Mazruiyah', 5, 'Petromin East'
    UNION ALL SELECT 'Jubail 1.', 34, 'Petromin Stock'
    UNION ALL SELECT 'Tahsilat Al Shaqeeq', 35, 'Petromin Stock'
    UNION ALL SELECT 'Unaizah-2.', 26, 'Petromin Stock'
    UNION ALL SELECT 'Neom', 18, 'Petromin Stock'
    UNION ALL SELECT 'ALKHADR', NULL, 'ALKHADR'
    UNION ALL SELECT 'Alalamiya', NULL, 'Tawuniya'
    UNION ALL SELECT 'Dream', NULL, 'Dream of Tech'
    UNION ALL SELECT 'Turbo Car Care', NULL, 'Turbo Car Care'
    UNION ALL SELECT 'PIT STOP', NULL, 'PIT STOP'
    UNION ALL SELECT 'Limar El-Shams', NULL, 'Limar El-Shams'
    UNION ALL SELECT 'AlMulhim', NULL, 'AlMulhim'
    UNION ALL SELECT 'Saptco - Riyadh', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Jeddah', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Dammam', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Makkah', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Taif', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Aseer', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Madina', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Jazan', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Qassim', NULL, 'Saptco'
    UNION ALL SELECT 'C-Naseem', NULL, 'Qparts'
    UNION ALL SELECT '-', NULL, 'Qparts'
    UNION ALL SELECT 'Asfan', NULL, 'Petromin - Body & Paint'
    UNION ALL SELECT 'Exit 17.', NULL, 'Petromin - Body & Paint'
    UNION ALL SELECT 'Branch 604.', NULL, 'Petromin - Body & Paint'
    UNION ALL SELECT 'Qassim 359.', NULL, 'Petromin - Body & Paint'
    UNION ALL SELECT 'Al-Munsiyah', NULL, 'Jeri Car Services'
    UNION ALL SELECT 'AlManar', NULL, 'Dream of Tech'
    UNION ALL SELECT 'AlMaghrizat', NULL, 'Dream of Tech'
    UNION ALL SELECT 'ELKhaleeg', NULL, 'Al Majdouie Riyadh'
    UNION ALL SELECT 'Elolyaa', NULL, 'Al Majdouie Riyadh'
    UNION ALL SELECT 'Aboor', 11, 'Petromin West'
    UNION ALL SELECT 'Al-Dammam', NULL, 'Petromin East'
    UNION ALL SELECT 'Al Zuimal', NULL, 'Petromin Stock'
    UNION ALL SELECT 'Al Narjis', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Al Nakheel', NULL, 'Petromin'
    UNION ALL SELECT 'AlQassim', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Al Rakah', NULL, 'Al Majdouie East'
    UNION ALL SELECT 'Al Taj', NULL, 'Petromin Stock'
    UNION ALL SELECT 'Azizia', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Badiya', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'C-Naseem', NULL, 'Qparts'
    UNION ALL SELECT 'Darb', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Dream', NULL, 'Dream of Tech'
    UNION ALL SELECT 'ELKhaleeg', NULL, 'Al Majdouie Riyadh'
    UNION ALL SELECT 'Elolyaa', NULL, 'Al Majdouie Riyadh'
    UNION ALL SELECT 'Exit 13.', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Exit 14.', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Exit 17.', NULL, 'Petromin - Body & Paint'
    UNION ALL SELECT 'Exit 18-', NULL, 'Petromin'
    UNION ALL SELECT 'Exit 18.', NULL, 'Petromin'
    UNION ALL SELECT 'Folan', NULL, 'Petromin Stock'
    UNION ALL SELECT 'Hamdaniya', NULL, 'Petromin West'
    UNION ALL SELECT 'Jalawia/DAMMAM', NULL, 'Petromin East'
    UNION ALL SELECT 'Jeddah', NULL, 'Petromin'
    UNION ALL SELECT 'Jubail 1.', NULL, 'Petromin Stock'
    UNION ALL SELECT 'Khamis Mushait', NULL, 'Petromin'
    UNION ALL SELECT 'Khurais', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Limar El-Shams', NULL, 'Limar El-Shams'
    UNION ALL SELECT 'Madinah Arbaeen.', NULL, 'Petromin West'
    UNION ALL SELECT 'Maj-Khurais', NULL, 'Petromin'
    UNION ALL SELECT 'Masif', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Mazruiyah', NULL, 'Petromin East'
    UNION ALL SELECT 'Nahada', NULL, 'Petromin West'
    UNION ALL SELECT 'Nasmat', NULL, 'Tawuniya'
    UNION ALL SELECT 'Neom', NULL, 'Petromin Stock'
    UNION ALL SELECT 'PIT STOP', NULL, 'PIT STOP'
    UNION ALL SELECT 'Qassim 359.', NULL, 'Petromin - Body & Paint'
    UNION ALL SELECT 'Rabea', NULL, 'Petromin West'
    UNION ALL SELECT 'Rashid mall/KHOBAR', NULL, 'Petromin East'
    UNION ALL SELECT 'Rayan/DAMMAM', NULL, 'Petromin East'
    UNION ALL SELECT 'Riyadh', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Saptco - Aseer', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Dammam', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Jazan', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Jeddah', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Madina', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Makkah', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Qassim', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Riyadh', NULL, 'Saptco'
    UNION ALL SELECT 'Saptco - Taif', NULL, 'Saptco'
    UNION ALL SELECT 'Sultan Bin Salman', NULL, 'Motor Lube'
    UNION ALL SELECT 'Tawuniya', NULL, 'Tawuniya'
    UNION ALL SELECT 'Thumama', NULL, 'Petromin Riyadh'
    UNION ALL SELECT 'Turbo Car Care', NULL, 'Turbo Car Care'
    UNION ALL SELECT 'Unaizah-2.', NULL, 'Petromin Stock'
)

-- Update user_data with branch mappings
-- This would need to be run with actual data from main branch
-- For now, let's show what the structure would look like
SELECT
    'Sample update query structure' as info,
    'UPDATE qvm_new_apps.user_data SET user_branch = bm.customer_id FROM branch_mappings bm WHERE email LIKE ''%pattern%''' as example_query;
