-- Vehicle models, by brand, for the RFQ form.
--
-- The vehicle brand on an RFQ has always been a list_data row (list car_brand); the model was free
-- text. This adds the models the team keeps for the Saudi market — 1297 of them across
-- 143 brands — so that choosing a brand offers its models, and typing something else
-- remains possible for the one that is not on the list.
--
-- Brands are matched to list_data BY NAME; the ids in the source sheet are ignored. 63 of
-- the sheet's brands had no list_data row and are added to the car_brand list here, so their models
-- have something to hang off. Where list_data already had the brand under a different spelling
-- (Mercedes-Benz / MERCEDES, Lincoln / LINCOLEN, Peugeot / PEOGEUT, Exeed / Exceed, Tank / TANK,
-- GREAT WALL, Mini / MINI COOPER) the existing row is used. list_data carries BYD twice; the lower id
-- is used, which is the deterministic choice until someone merges them.

CREATE TABLE IF NOT EXISTS qvm_new_apps.vehicle_models (
  model_id   bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  brand_id   bigint  NOT NULL REFERENCES qvm_new_apps.list_data (list_data_id),
  name_en    text    NOT NULL,
  name_ar    text,
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_vehicle_models_brand_name
  ON qvm_new_apps.vehicle_models (brand_id, lower(name_en));
GRANT ALL ON qvm_new_apps.vehicle_models TO service_role;
GRANT SELECT ON qvm_new_apps.vehicle_models TO authenticated;

-- ── Brands the sheet has that list_data did not ───────────────────────────────────────────────
INSERT INTO qvm_new_apps.list_data (list_id, list_data)
SELECT l.list_id, v.name
  FROM qvm_new_apps.lists l
  CROSS JOIN (VALUES
  ('Opel'),
  ('Buick'),
  ('Proton'),
  ('ZXAUTO'),
  ('Lifan'),
  ('VICTORY AUTO'),
  ('CMC'),
  ('Soueast'),
  ('Mahindra'),
  ('Zotye'),
  ('INEOS'),
  ('Lotus'),
  ('Huanghai'),
  ('OMODA'),
  ('ROX'),
  ('KAIYI'),
  ('Borgward'),
  ('Sandstorm'),
  ('Dorcen'),
  ('Al Damani'),
  ('Seres'),
  ('Avatr'),
  ('Riddara'),
  ('MHERO'),
  ('IM Motors'),
  ('Denza'),
  ('ZNA'),
  ('Morgan'),
  ('DFSK'),
  ('Skywell'),
  ('Yangwang'),
  ('Xpeng'),
  ('Cupra'),
  ('212'),
  ('Theeb'),
  ('Devel'),
  ('Ariel'),
  ('Force'),
  ('Rabdan'),
  ('ZEEKR'),
  ('Li Auto'),
  ('Voyah'),
  ('JIDU'),
  ('Deepal'),
  ('Alpine'),
  ('Freelander'),
  ('King Long'),
  ('Zarooq Motors'),
  ('W Motors'),
  ('Polestar'),
  ('Forthing'),
  ('NIO'),
  ('VGV'),
  ('AITO'),
  ('VinFast'),
  ('Xiaomi Auto'),
  ('Roewe'),
  ('iCAUR'),
  ('Brilliance'),
  ('Other'),
  ('Parts & Accessories'),
  ('Trucks and heavy equipment'),
  ('Motorcycles')
  ) AS v(name)
 WHERE l.list_name = 'car_brand'
   AND NOT EXISTS (SELECT 1 FROM qvm_new_apps.list_data ld
                    WHERE ld.list_id = l.list_id AND lower(btrim(ld.list_data)) = lower(v.name));

-- ── The models ────────────────────────────────────────────────────────────────────────────────
INSERT INTO qvm_new_apps.vehicle_models (brand_id, name_en, name_ar)
SELECT b.list_data_id, v.model_en, v.model_ar
  FROM (VALUES
  ('TOYOTA', 'Avalon', 'افالون'),
  ('TOYOTA', 'XA', 'إكس إيه'),
  ('TOYOTA', 'Aurion', 'اوريون'),
  ('TOYOTA', 'Eco', 'ايكو'),
  ('TOYOTA', 'Innova', 'انوفا'),
  ('TOYOTA', 'Bus', 'باص'),
  ('TOYOTA', 'Land Cruiser Prado', 'برادو'),
  ('TOYOTA', 'Previa', 'بريفيا'),
  ('TOYOTA', 'RAV4', 'راف فور'),
  ('TOYOTA', 'Sequoia', 'سيكويا'),
  ('TOYOTA', 'Supra', 'سوبرا'),
  ('TOYOTA', 'Fortuner', 'فورتشنر'),
  ('TOYOTA', 'Camry', 'كامري'),
  ('TOYOTA', 'Cressida', 'كرسيدا'),
  ('TOYOTA', 'Corolla', 'كورولا'),
  ('TOYOTA', 'Land Cruiser', 'لاندكروزر'),
  ('TOYOTA', 'Yaris', 'يارس'),
  ('TOYOTA', 'Highlander', 'هايلاندر'),
  ('TOYOTA', 'Hilux', 'هايلوكس'),
  ('TOYOTA', 'Land Cruiser Pick Up', 'شاص'),
  ('TOYOTA', 'Land Cruiser 70 Series', 'ربع'),
  ('TOYOTA', 'FJ Cruiser', 'اف جي'),
  ('TOYOTA', 'Tundra', 'تندرا'),
  ('TOYOTA', 'GR 86', 'جي آر 86'),
  ('TOYOTA', 'Avanza', 'افانزا'),
  ('TOYOTA', 'Prius', 'بريوس'),
  ('TOYOTA', 'Rush', 'راش'),
  ('TOYOTA', 'Granvia', 'جرانفيا'),
  ('TOYOTA', 'C HR', 'سي إتش آر'),
  ('TOYOTA', 'Corolla Cross', 'كورولا كروس'),
  ('TOYOTA', 'Raize', 'رايز'),
  ('TOYOTA', 'Veloz', 'فيلوز'),
  ('TOYOTA', 'Crown', 'كراون'),
  ('TOYOTA', 'Urban Cruiser', 'اوربان كروزر'),
  ('TOYOTA', 'Liteace', 'لايت ايس'),
  ('TOYOTA', 'Coaster', 'كوستر'),
  ('TOYOTA', 'Hiace', 'هايس'),
  ('TOYOTA', 'Other', 'أخرى'),
  ('Nissan', 'Maxima', 'مكسيما'),
  ('Nissan', 'Pickup', 'ددسن'),
  ('Nissan', 'Murano', 'مورانو'),
  ('Nissan', 'Altima', 'التيما'),
  ('Nissan', 'Gloria', 'جلوريا'),
  ('Nissan', 'Pathfinder', 'باثفندر'),
  ('Nissan', 'Primera', 'بريميرا'),
  ('Nissan', 'Patrol', 'باترول'),
  ('Nissan', 'Skyline', 'سكاي لاين'),
  ('Nissan', 'Sunny', 'صني'),
  ('Nissan', 'X-Trail', 'اكس تريل'),
  ('Nissan', 'Xterra', 'اكستيرا'),
  ('Nissan', 'Tiida', 'تيدا'),
  ('Nissan', 'Armada', 'ارمادا'),
  ('Nissan', 'Navara', 'نافارا'),
  ('Nissan', 'Patrol Pick Up', 'نيسان شاص'),
  ('Nissan', 'Urvan', 'اورفان'),
  ('Nissan', 'Terrano', 'تيرانو'),
  ('Nissan', 'Z', 'فئة زد'),
  ('Nissan', 'Qashqai', 'قاشقاي'),
  ('Nissan', 'Sentra', 'سنترا'),
  ('Nissan', 'Juke', 'جوك'),
  ('Nissan', 'Kicks', 'كيكس'),
  ('Nissan', 'GT-R', 'جي تي آر'),
  ('Nissan', '370Z', '370 زد'),
  ('Nissan', 'Civilian', 'سيفيليان'),
  ('Nissan', 'Patrol Safari', 'باترول سفاري'),
  ('Nissan', 'Cedric', 'سيدرك'),
  ('Nissan', 'Patrol NISMO', 'باترول نيسمو'),
  ('Nissan', 'Micra', 'ميكرا'),
  ('Nissan', 'Magnite', 'ماجنيت'),
  ('Nissan', 'Ariya', 'آريا'),
  ('Nissan', 'Leaf', 'ليف'),
  ('Nissan', 'Tekton', 'تيكتون'),
  ('Nissan', 'Other', 'أخرى'),
  ('LEXUS', 'ES', 'إي إس'),
  ('LEXUS', 'GS', 'جي إس'),
  ('LEXUS', 'IS', 'آي إس'),
  ('LEXUS', 'LS', 'إل إس'),
  ('LEXUS', 'LX', 'إل إكس'),
  ('LEXUS', 'RX', 'آر إكس'),
  ('LEXUS', 'GX', 'جي إكس'),
  ('LEXUS', 'SC', 'إس سي'),
  ('LEXUS', 'NX', 'إن إكس'),
  ('LEXUS', 'UX', 'يو إكس'),
  ('LEXUS', 'RC', 'آر سي'),
  ('LEXUS', 'RC F', 'آر سي إف'),
  ('LEXUS', 'LC', 'إل سي'),
  ('LEXUS', 'GSF', 'جي إس إف'),
  ('LEXUS', 'UX 200', 'يو إكس 200'),
  ('LEXUS', 'LC 500', 'إل سي 500'),
  ('LEXUS', 'LC 500h', 'إل سي 500 إتش'),
  ('LEXUS', 'IS 350', 'آي إس 350'),
  ('LEXUS', 'RX 350', 'آر إكس 350'),
  ('LEXUS', 'ES 350', 'إي إس 350'),
  ('LEXUS', 'IS 300', 'آي إس 300'),
  ('LEXUS', 'LS 460', 'إل إس 460'),
  ('LEXUS', 'LS 460L', 'إل إس 460 إل'),
  ('LEXUS', 'LS 600hL', 'إل إس 600 إتش إل'),
  ('LEXUS', 'LX 570', 'إل إكس 570'),
  ('LEXUS', 'GX 460', 'جي إكس 460'),
  ('LEXUS', 'Other', 'أخرى'),
  ('MERCEDES', 'SE', 'إس إي'),
  ('MERCEDES', 'SL', 'إس إل'),
  ('MERCEDES', 'SEL', 'إس إي إل'),
  ('MERCEDES', 'SEC', 'إس إي سي'),
  ('MERCEDES', 'CL', 'سي إل'),
  ('MERCEDES', 'CLK', 'سي إل كيه'),
  ('MERCEDES', 'CLS', 'سي إل إس'),
  ('MERCEDES', 'ML', 'إم إل'),
  ('MERCEDES', 'SLK', 'إس إل كيه'),
  ('MERCEDES', 'AMG', 'إيه إم جي'),
  ('MERCEDES', 'G', 'الفئة جي'),
  ('MERCEDES', 'E', 'الفئة إي'),
  ('MERCEDES', 'C', 'الفئة سي'),
  ('MERCEDES', 'S', 'الفئة إس'),
  ('MERCEDES', 'CLA', 'سي إل إيه'),
  ('MERCEDES', 'GLA', 'جي إل إيه'),
  ('MERCEDES', 'GLC', 'جي إل سي'),
  ('MERCEDES', 'GLE', 'جي إل إي'),
  ('MERCEDES', 'GLS', 'جي إل إس'),
  ('MERCEDES', 'V', 'الفئة في'),
  ('MERCEDES', 'A', 'الفئة إيه'),
  ('MERCEDES', 'SLC', 'إس إل سي'),
  ('MERCEDES', 'Maybach', 'مايباخ'),
  ('MERCEDES', 'AMG GT', 'إيه إم جي جي تي'),
  ('MERCEDES', 'B', 'الفئة بي'),
  ('MERCEDES', 'GL', 'جي إل'),
  ('MERCEDES', 'GLK', 'جي إل كيه'),
  ('MERCEDES', 'R', 'الفئة آر'),
  ('MERCEDES', 'GTS', 'جي تي إس'),
  ('MERCEDES', 'Van Sprinter', 'فان سبرنتر'),
  ('MERCEDES', 'GLB', 'جي إل بي'),
  ('MERCEDES', 'EQA', 'إي كيو إيه'),
  ('MERCEDES', 'EQB', 'إي كيو بي'),
  ('MERCEDES', 'EQE', 'إي كيو إي'),
  ('MERCEDES', 'EQS', 'إي كيو إس'),
  ('MERCEDES', 'CLE', 'سي إل إي'),
  ('MERCEDES', 'Maybach GLS', 'مايباخ جي إل إس'),
  ('MERCEDES', 'A35 AMG', 'إيه 35 إيه إم جي'),
  ('MERCEDES', 'EQC', 'إي كيو سي'),
  ('MERCEDES', 'EQE SUV', 'إي كيو إي إس يو في'),
  ('MERCEDES', 'EQS SUV', 'إي كيو إس إس يو في'),
  ('MERCEDES', 'EQV', 'إي كيو في'),
  ('MERCEDES', 'GLC-250', 'جي إل سي 250'),
  ('MERCEDES', 'BRABUS', 'برابوس'),
  ('MERCEDES', 'G 63 AMG', 'جي 63 إيه إم جي'),
  ('MERCEDES', 'CLC-200', 'سي إل سي 200'),
  ('MERCEDES', 'Other', 'أخرى'),
  ('PORSCHE', '911', '911'),
  ('PORSCHE', 'Cayenne', 'كايين'),
  ('PORSCHE', 'Boxster', 'بوكستر'),
  ('PORSCHE', 'Carrera', 'كاريرا'),
  ('PORSCHE', 'Cayman', 'كايمن'),
  ('PORSCHE', 'Turbo', 'توربو'),
  ('PORSCHE', 'GT', 'جي تي'),
  ('PORSCHE', 'Panamera', 'باناميرا'),
  ('PORSCHE', 'Macan', 'ماكان'),
  ('PORSCHE', '718', '718'),
  ('PORSCHE', 'Taycan', 'تايكان'),
  ('PORSCHE', 'Carrera GT', 'كاريرا جي تي'),
  ('PORSCHE', 'GT2', 'جي تي 2'),
  ('PORSCHE', 'Other', 'أخرى'),
  ('FORD', 'Crown Victoria', 'كراون فكتوريا'),
  ('FORD', 'Escape', 'اسكيب'),
  ('FORD', 'Ex-Corgan', 'اكس كورجن'),
  ('FORD', 'Expedition', 'اكسبيدشن'),
  ('FORD', 'Explorer', 'اكسبلورر'),
  ('FORD', 'Grand Marquis', 'جراند ماركيز'),
  ('FORD', 'Mondeo', 'مونديو'),
  ('FORD', 'Mustang', 'موستنج'),
  ('FORD', 'Pick up', 'بيك اب'),
  ('FORD', 'F-150', 'إف 150'),
  ('FORD', 'f250', 'إف 250'),
  ('FORD', 'f350', 'إف 350'),
  ('FORD', 'Ranger', 'رينجر'),
  ('FORD', 'Splash', 'سبلاش'),
  ('FORD', 'Taurus', 'توروس'),
  ('FORD', 'Thunderbird', 'ثندريبرد'),
  ('FORD', 'Windstar', 'وندستار'),
  ('FORD', 'Cougar', 'كوجر'),
  ('FORD', 'Fox', 'فوكس'),
  ('FORD', 'Flex', 'فلكس'),
  ('FORD', 'Fusion', 'فيوجن'),
  ('FORD', 'Edge', 'ايدج'),
  ('FORD', 'Figo', 'فيجو'),
  ('FORD', 'Escort', 'إسكورت'),
  ('FORD', 'F550', 'إف 550'),
  ('FORD', 'F450', 'إف 450'),
  ('FORD', 'vans ford', 'فان فورد'),
  ('FORD', 'EcoSport', 'إيكوسبورت'),
  ('FORD', 'Bronco', 'برونكو'),
  ('FORD', 'Territory', 'تيريتوري'),
  ('FORD', 'Everest', 'ايفرست'),
  ('FORD', 'Bronco Sport', 'برونكو سبورت'),
  ('FORD', 'F-150 Lightning', 'إف 150 لايتنينج'),
  ('FORD', 'Mustang Mach-E', 'مستانغ ماك-إي'),
  ('FORD', 'Super Duty', 'سوبر ديوتي'),
  ('FORD', 'Transit', 'ترانزيت'),
  ('FORD', 'Other', 'أخرى'),
  ('ISUZU', 'Ascender', 'اسندر'),
  ('ISUZU', 'D-MAX', 'ديماكس'),
  ('ISUZU', 'MUX', 'إم يو إكس'),
  ('ISUZU', 'Reward', 'ريوارد'),
  ('ISUZU', 'NPR', 'إن بي آر'),
  ('ISUZU', 'Other', 'أخرى'),
  ('CHEVROLET', 'Uplander', 'ابلاندر'),
  ('CHEVROLET', 'Epica', 'ابيكا'),
  ('CHEVROLET', 'Aveo', 'افيو'),
  ('CHEVROLET', 'Astro Van', 'استروفان'),
  ('CHEVROLET', 'Avalanche', 'افلانش'),
  ('CHEVROLET', 'Express Van', 'اكسبرس فان'),
  ('CHEVROLET', 'Impala', 'امبالا'),
  ('CHEVROLET', 'Optra', 'اوبترا'),
  ('CHEVROLET', 'Blazer', 'بليزر'),
  ('CHEVROLET', 'Tahoe', 'تاهو'),
  ('CHEVROLET', 'Trailblazer', 'تريل بليزر'),
  ('CHEVROLET', 'Traverse', 'ترافيرس'),
  ('CHEVROLET', 'G Van', 'جي فان'),
  ('CHEVROLET', 'Suburban', 'سوبربان'),
  ('CHEVROLET', 'Van', 'فان'),
  ('CHEVROLET', 'Venture', 'فنشر'),
  ('CHEVROLET', 'Captiva', 'كابتيفا'),
  ('CHEVROLET', 'Caprice', 'كابريس'),
  ('CHEVROLET', 'Cruze', 'كروز'),
  ('CHEVROLET', 'Cavalier', 'كافالير'),
  ('CHEVROLET', 'Caravan', 'كرفان'),
  ('CHEVROLET', 'Camaro', 'كمارو'),
  ('CHEVROLET', 'Corvette', 'كورفيت'),
  ('CHEVROLET', 'Malibu', 'ماليبو'),
  ('CHEVROLET', 'Sonic', 'سونيك'),
  ('CHEVROLET', 'Silverado', 'سلفرادو'),
  ('CHEVROLET', 'Spark', 'سبارك'),
  ('CHEVROLET', 'Colorado', 'كولورادو'),
  ('CHEVROLET', 'Lumina', 'لومينا'),
  ('CHEVROLET', 'Bolt', 'بولت'),
  ('CHEVROLET', 'Equinox', 'اكوينوكس'),
  ('CHEVROLET', 'Groove', 'جروف'),
  ('CHEVROLET', 'Trax', 'تراكس'),
  ('CHEVROLET', 'Onix', 'اونيكس'),
  ('CHEVROLET', 'Other', 'أخرى'),
  ('GMC', 'Suburban', 'سوبربان'),
  ('GMC', 'Van', 'فان'),
  ('GMC', 'Terrain', 'تيرين'),
  ('GMC', 'Envoy', 'انفوي'),
  ('GMC', 'Jimmy', 'جيمي'),
  ('GMC', 'Safari', 'سفاري'),
  ('GMC', 'Savana', 'سافانا'),
  ('GMC', 'Pick up', 'بيك أب'),
  ('GMC', 'Yukon', 'يوكن'),
  ('GMC', 'Acadia', 'اكاديا'),
  ('GMC', 'Sierra', 'سييرا'),
  ('GMC', 'Canyon', 'كانيون'),
  ('GMC', 'Hummer EV Pickup', 'همر إي في بيك أب'),
  ('GMC', 'Hummer EV SUV', 'همر إي في إس يو في'),
  ('GMC', 'Sierra HD', 'سييرا إتش دي'),
  ('GMC', 'Other', 'أخرى'),
  ('BMW', '1 Series', 'الفئة الأولى'),
  ('BMW', '3 Series', 'الفئة الثالثة'),
  ('BMW', '5 Series', 'الفئة الخامسة'),
  ('BMW', '6 Series', 'الفئة السادسة'),
  ('BMW', '7 Series', 'الفئة السابعة'),
  ('BMW', 'Z4', 'زد 4'),
  ('BMW', 'M', 'الفئة إم'),
  ('BMW', 'X', 'الفئة إكس'),
  ('BMW', 'Mini Cooper', 'ميني كوبر'),
  ('BMW', '2 Series', 'الفئة الثانية'),
  ('BMW', '4 Series', 'الفئة الرابعة'),
  ('BMW', '8 Series', 'الفئة الثامنة'),
  ('BMW', 'i', 'الفئة آي'),
  ('BMW', 'i7', 'آي 7'),
  ('BMW', 'M5', 'إم 5'),
  ('BMW', 'M3', 'إم 3'),
  ('BMW', 'M4', 'إم 4'),
  ('BMW', 'X6', 'إكس 6'),
  ('BMW', 'X1', 'إكس 1'),
  ('BMW', 'i3', 'آي 3'),
  ('BMW', 'i4', 'آي 4'),
  ('BMW', 'i5', 'آي 5'),
  ('BMW', 'iX', 'آي إكس'),
  ('BMW', 'iX1', 'آي إكس 1'),
  ('BMW', 'iX3', 'آي إكس 3'),
  ('BMW', 'M8', 'إم 8'),
  ('BMW', 'X2', 'إكس 2'),
  ('BMW', 'X7', 'إكس 7'),
  ('BMW', 'XM', 'إكس إم'),
  ('BMW', 'M2', 'إم 2'),
  ('BMW', 'X3', 'إكس 3'),
  ('BMW', 'X4', 'إكس 4'),
  ('BMW', 'X5', 'إكس 5'),
  ('BMW', 'X5 M', 'إكس 5 إم'),
  ('BMW', 'X6 M', 'إكس 6 إم'),
  ('BMW', 'Other', 'أخرى'),
  ('JEEP', 'Cherokee', 'شيروكي'),
  ('JEEP', 'Grand Cherokee', 'جراند شيروكي'),
  ('JEEP', 'Wrangler', 'رانجلر'),
  ('JEEP', 'Liberty', 'ليبرتي'),
  ('JEEP', 'Renegade', 'رينيجيد'),
  ('JEEP', 'Compass', 'كومباس'),
  ('JEEP', 'Gladiator', 'جلاديتور'),
  ('JEEP', 'Grand Wagoneer', 'جراند واجونير'),
  ('JEEP', 'Commander', 'كوماندر'),
  ('JEEP', 'Wagoneer', 'واجونير'),
  ('JEEP', 'Other', 'أخرى'),
  ('HYUNDAI', 'Accent', 'اكسنت'),
  ('HYUNDAI', 'Sonata', 'سوناتا'),
  ('HYUNDAI', 'Santa Fe', 'سنتافي'),
  ('HYUNDAI', 'Coupe', 'كوبية'),
  ('HYUNDAI', 'Elantra', 'النترا'),
  ('HYUNDAI', 'Azera', 'ازيرا'),
  ('HYUNDAI', 'Galloper', 'جالوير'),
  ('HYUNDAI', 'Terracan', 'تيريكان'),
  ('HYUNDAI', 'Tucson', 'توسان'),
  ('HYUNDAI', 'Matrix', 'ماتريكس'),
  ('HYUNDAI', 'H1', 'إتش 1'),
  ('HYUNDAI', 'Veracruz', 'فيراكروز'),
  ('HYUNDAI', 'Veloster', 'فيلوستر'),
  ('HYUNDAI', 'Centennial', 'سنتنيال'),
  ('HYUNDAI', 'Trajet', 'تراجيت'),
  ('HYUNDAI', 'i40', 'آي 40'),
  ('HYUNDAI', 'i10', 'آي 10'),
  ('HYUNDAI', 'Kona', 'كونا'),
  ('HYUNDAI', 'Creta', 'كريتا'),
  ('HYUNDAI', 'Palisade', 'باليسيد'),
  ('HYUNDAI', 'Grand Santa Fe', 'جراند سنتافي'),
  ('HYUNDAI', 'i30', 'آي 30'),
  ('HYUNDAI', 'Venue', 'فينيو'),
  ('HYUNDAI', 'Staria', 'ستاريا'),
  ('HYUNDAI', 'Stargazer', 'ستارجيزر'),
  ('HYUNDAI', 'Ioniq 6', 'ايونيك 6'),
  ('HYUNDAI', 'Ioniq 5', 'ايونيك 5'),
  ('HYUNDAI', 'Grand Creta', 'جراند كريتا'),
  ('HYUNDAI', 'Veloster N', 'فيلوستر إن'),
  ('HYUNDAI', 'Grand i10', 'جراند آي 10'),
  ('HYUNDAI', 'Ioniq', 'أيونك'),
  ('HYUNDAI', 'Other', 'أخرى'),
  ('HONDA', 'Accord', 'اكورد'),
  ('HONDA', 'Civic', 'سيفيك'),
  ('HONDA', 'CR-V', 'سي آر في'),
  ('HONDA', 'Legend', 'ليجيند'),
  ('HONDA', 'Odyssey', 'اوديسي'),
  ('HONDA', 'Integra', 'انتيجرا'),
  ('HONDA', 'Prelude', 'بريليود'),
  ('HONDA', 'Pilot', 'بايلوت'),
  ('HONDA', 'City', 'سيتي'),
  ('HONDA', 'HR-V', 'إتش آر في'),
  ('HONDA', 'ZR-V', 'زد آر في'),
  ('HONDA', 'Civic Type R', 'سيفيك تايب ار'),
  ('HONDA', 'E', 'إي'),
  ('HONDA', 'Odyssey J', 'اوديسي جاي'),
  ('HONDA', 'Other', 'أخرى'),
  ('HUMMER', 'H1', 'إتش 1'),
  ('HUMMER', 'H2', 'إتش 2'),
  ('HUMMER', 'H3', 'إتش 3'),
  ('HUMMER', 'Other', 'أخرى'),
  ('INFINITI', 'FX', 'إف إكس'),
  ('INFINITI', 'G', 'انفنيتي جي'),
  ('INFINITI', 'QX', 'كيو إكس'),
  ('INFINITI', 'Q', 'كيو'),
  ('INFINITI', 'M', 'إم'),
  ('INFINITI', 'Q30', 'كيو 30'),
  ('INFINITI', 'Q50', 'كيو 50'),
  ('INFINITI', 'Q60', 'كيو 60'),
  ('INFINITI', 'Q70', 'كيو 70'),
  ('INFINITI', 'QX50', 'كيو إكس 50'),
  ('INFINITI', 'QX60', 'كيو إكس 60'),
  ('INFINITI', 'QX70', 'كيو إكس 70'),
  ('INFINITI', 'QX80', 'كيو إكس 80'),
  ('INFINITI', 'QX56', 'كيو إكس 56'),
  ('INFINITI', 'QX55', 'كيو إكس 55'),
  ('INFINITI', 'Other', 'أخرى'),
  ('LANDROVER', 'Discovery', 'ديسكفري'),
  ('LANDROVER', 'Range Rover', 'رنج روفر'),
  ('LANDROVER', 'Freelander', 'فريلاندر'),
  ('LANDROVER', 'LR2', 'إل آر 2'),
  ('LANDROVER', 'LR3', 'إل آر 3'),
  ('LANDROVER', 'Defender', 'ديفندر'),
  ('LANDROVER', 'LR4', 'إل آر 4'),
  ('LANDROVER', 'Range Rover Velar', 'فيلار'),
  ('LANDROVER', 'Range Rover Evoque', 'ايفوك'),
  ('LANDROVER', 'Range Rover Sport', 'رينج روفر سبورت'),
  ('LANDROVER', 'Discovery Sport', 'ديسكفري سبورت'),
  ('LANDROVER', 'Range Rover SV', 'رنج روفر إس في'),
  ('LANDROVER', 'HSE V8', 'إتش إس إي في 8'),
  ('LANDROVER', 'Other', 'أخرى'),
  ('Mazda', '323', '323'),
  ('Mazda', '626', '626'),
  ('Mazda', 'MPV', 'إم بي في'),
  ('Mazda', 'Mazda 3', 'مازدا 3'),
  ('Mazda', 'Mazda 6', 'مازدا 6'),
  ('Mazda', 'RX8', 'آر إكس 8'),
  ('Mazda', 'BT50', 'بي تي 50'),
  ('Mazda', 'CX-9', 'سي إكس 9'),
  ('Mazda', 'CX7', 'سي إكس 7'),
  ('Mazda', 'CX2', 'سي إكس 2'),
  ('Mazda', 'MX-5', 'إم إكس 5'),
  ('Mazda', 'CX-5', 'سي إكس 5'),
  ('Mazda', 'Mazda 2', 'مازدا 2'),
  ('Mazda', 'Mazda 5', 'مازدا 5'),
  ('Mazda', 'CX-3', 'سي إكس 3'),
  ('Mazda', 'CX-30', 'سي إكس 30'),
  ('Mazda', 'CX-90', 'سي إكس 90'),
  ('Mazda', 'CX-60', 'سي إكس 60'),
  ('Mazda', 'MX-30', 'إم إكس 30'),
  ('Mazda', 'Other', 'أخرى'),
  ('Mercury', 'Mountaineer', 'مونتنير'),
  ('Mercury', 'Marauder', 'مارودر'),
  ('Mercury', 'Other', 'أخرى'),
  ('VOLKSWAGEN', 'Beetle', 'بيتل'),
  ('VOLKSWAGEN', 'Golf', 'جولف'),
  ('VOLKSWAGEN', 'Passat', 'باسات'),
  ('VOLKSWAGEN', 'Polo', 'بولو'),
  ('VOLKSWAGEN', 'Touareg', 'طوارق'),
  ('VOLKSWAGEN', 'Scirocco', 'شيروكو'),
  ('VOLKSWAGEN', 'Jetta', 'جيتا'),
  ('VOLKSWAGEN', 'Tiguan', 'تيجوان'),
  ('VOLKSWAGEN', 'Teramont', 'تيرامونت'),
  ('VOLKSWAGEN', 'T-Roc', 'تي روك'),
  ('VOLKSWAGEN', 'Arteon', 'ارتيون'),
  ('VOLKSWAGEN', 'Amarok', 'اماروك'),
  ('VOLKSWAGEN', 'Golf GTI', 'جولف جي تي أي'),
  ('VOLKSWAGEN', 'Golf R', 'جولف آر'),
  ('VOLKSWAGEN', 'Other', 'أخرى'),
  ('MITSUBISHI', 'Colt', 'كولت'),
  ('MITSUBISHI', 'Galant', 'جالنت'),
  ('MITSUBISHI', 'Lancer', 'لانسر'),
  ('MITSUBISHI', 'Magna', 'ماجنا'),
  ('MITSUBISHI', 'Nativa', 'ناتيفا'),
  ('MITSUBISHI', 'Pajero', 'باجيرو'),
  ('MITSUBISHI', 'L200', 'إل 200'),
  ('MITSUBISHI', 'Sigma', 'سيجما'),
  ('MITSUBISHI', 'Spacestar', 'سبيس ستار'),
  ('MITSUBISHI', 'Outlander', 'اوتلاندر'),
  ('MITSUBISHI', 'Eclipse Cross', 'اكليبس كروس'),
  ('MITSUBISHI', 'Attrage', 'اتراج'),
  ('MITSUBISHI', 'ASX', 'إيه إس إكس'),
  ('MITSUBISHI', 'Montero', 'مونتيرو'),
  ('MITSUBISHI', 'Grandis', 'جرانديز'),
  ('MITSUBISHI', 'Xpander', 'اكسباندر'),
  ('MITSUBISHI', 'Xpander Cross', 'اكسباندر كروس'),
  ('MITSUBISHI', 'Destinator', 'ديستينيتور'),
  ('MITSUBISHI', 'Montero Sport', 'مونتيرو سبورت'),
  ('MITSUBISHI', 'Pickup', 'بيك اب'),
  ('MITSUBISHI', 'FUSO', 'فوسو'),
  ('MITSUBISHI', 'Lancer EX', 'لانسر إي اكس'),
  ('MITSUBISHI', 'Other', 'أخرى'),
  ('LINCOLEN', 'Navigator', 'نافيجتور'),
  ('LINCOLEN', 'MKS', 'إم كيه إس'),
  ('LINCOLEN', 'LS', 'ال اس'),
  ('LINCOLEN', 'Town Car', 'تاون كار'),
  ('LINCOLEN', 'Nautilus', 'نوتيلوس'),
  ('LINCOLEN', 'Continental', 'كونتيننتال'),
  ('LINCOLEN', 'Aviator', 'افياتور'),
  ('LINCOLEN', 'Corsair', 'كورسير'),
  ('LINCOLEN', 'MKX', 'إم كيه إكس'),
  ('LINCOLEN', 'Other', 'أخرى'),
  ('Opel', 'Astra', 'استرا'),
  ('Opel', 'Rekord', 'ريكورد'),
  ('Opel', 'Crossland', 'كروسلاند'),
  ('Opel', 'Crossland X', 'كروسلاند إكس'),
  ('Opel', 'Grandland X', 'جراندلاند إكس'),
  ('Opel', 'Vivaro', 'فيفارو'),
  ('Opel', 'Zafira Life', 'زافيرا لايف'),
  ('Opel', 'Other', 'أخرى'),
  ('KIA', 'Carens', 'كارينز'),
  ('KIA', 'Carnival', 'كارنيفال'),
  ('KIA', 'Optima', 'اوبتيما'),
  ('KIA', 'Sportage', 'سبورتاج'),
  ('KIA', 'Sephia', 'سيفيا'),
  ('KIA', 'Cerato', 'سيراتو'),
  ('KIA', 'Cadenza', 'كادينزا'),
  ('KIA', 'Mohave', 'موهافي'),
  ('KIA', 'Sorento', 'سورنتو'),
  ('KIA', 'Picanto', 'بيكانتو'),
  ('KIA', 'Rio', 'ريو'),
  ('KIA', 'Opirus', 'اوبيروس'),
  ('KIA', 'Koris', 'كوريس'),
  ('KIA', 'Soul', 'سول'),
  ('KIA', 'Pegas', 'بيجاس'),
  ('KIA', 'Stinger', 'ستينجر'),
  ('KIA', 'K900', 'كيه 900'),
  ('KIA', 'Telluride', 'تيلورايد'),
  ('KIA', 'Seltos', 'سيلتوس'),
  ('KIA', 'Niro', 'نيرو'),
  ('KIA', 'K5', 'كيه 5'),
  ('KIA', 'Sonet', 'سونيت'),
  ('KIA', 'K8', 'كيه 8'),
  ('KIA', 'K3', 'كيه 3'),
  ('KIA', 'K4', 'كيه 4'),
  ('KIA', 'Tasman', 'تاسمان'),
  ('KIA', 'Stonic', 'ستونيك'),
  ('KIA', 'EV9', 'إي في 9'),
  ('KIA', 'EV5', 'إي في 5'),
  ('KIA', 'EV6', 'إي في 6'),
  ('KIA', 'Other', 'أخرى'),
  ('MASERATI', 'Mazzarini', 'مازيراني'),
  ('MASERATI', 'Ghibli', 'جيبلي'),
  ('MASERATI', 'Levante', 'ليفانتي'),
  ('MASERATI', 'Quattroporte', 'كواتربورتي'),
  ('MASERATI', 'GranTurismo', 'جران توريزمو'),
  ('MASERATI', 'Grecale', 'جريكالي'),
  ('MASERATI', 'GranCabrio', 'جران كابريو'),
  ('MASERATI', 'MC20', 'إم سي 20'),
  ('MASERATI', 'MC20 Cielo', 'إم سي 20 سييلو'),
  ('MASERATI', 'Other', 'أخرى'),
  ('BENTLEY', 'Flying Spur', 'كونتيننتال فلاينج سبير'),
  ('BENTLEY', 'Arnage', 'ارنيج'),
  ('BENTLEY', 'Continental GT', 'كونتيننتال جي تي'),
  ('BENTLEY', 'Continental GTC', 'كونتيننتال جي تي سي'),
  ('BENTLEY', 'Azure', 'ازيور'),
  ('BENTLEY', 'Brooklands', 'بروكلاندز'),
  ('BENTLEY', 'Bentayga', 'بنتياقا'),
  ('BENTLEY', 'Mulsanne', 'مولسان'),
  ('BENTLEY', 'EXP 100 GT', 'إي إكس بي 100 جي تي'),
  ('BENTLEY', 'Other', 'أخرى'),
  ('ASTON MARTIN', 'Vantage', 'فانتاج'),
  ('ASTON MARTIN', 'DB11', 'دي بي 11'),
  ('ASTON MARTIN', 'DBS', 'دي بي إس'),
  ('ASTON MARTIN', 'Rapide S', 'رابيد اس'),
  ('ASTON MARTIN', 'DB12', 'دي بي 12'),
  ('ASTON MARTIN', 'DBX', 'دي بي إكس'),
  ('ASTON MARTIN', 'Valhalla', 'فالهالا'),
  ('ASTON MARTIN', 'Rapide AMR', 'رابيد أس'),
  ('ASTON MARTIN', 'Other', 'أخرى'),
  ('CADILLAC', 'Concours', 'كونكورس'),
  ('CADILLAC', 'Deville', 'ديفيل'),
  ('CADILLAC', 'Escalade', 'اسكاليد'),
  ('CADILLAC', 'Fleetwood', 'فليتوود'),
  ('CADILLAC', 'STS', 'إس تي إس'),
  ('CADILLAC', 'SRX', 'إس آر إكس'),
  ('CADILLAC', 'CTS', 'سي تي إس'),
  ('CADILLAC', 'DTS', 'دي تي إس'),
  ('CADILLAC', 'CT6', 'سي تي 6'),
  ('CADILLAC', 'XT4', 'إكس تي 4'),
  ('CADILLAC', 'XT5', 'إكس تي 5'),
  ('CADILLAC', 'XT6', 'إكس تي 6'),
  ('CADILLAC', 'CT4', 'سي تي 4'),
  ('CADILLAC', 'CT5', 'سي تي 5'),
  ('CADILLAC', 'ATS', 'إيه تي إس'),
  ('CADILLAC', 'CT4-V Blackwing', 'سي تي 4- في بلاكوينغ'),
  ('CADILLAC', 'CT5-V Blackwing', 'سي تي 5- في بلاكوينغ'),
  ('CADILLAC', 'Eldorado', 'إلدورادو'),
  ('CADILLAC', 'Other', 'أخرى'),
  ('CHRYSLER', 'Concorde', 'كونكورد'),
  ('CHRYSLER', 'Imperial', 'امبيريال'),
  ('CHRYSLER', 'Grand Voyager', 'جراند فوياجر'),
  ('CHRYSLER', 'M300', 'إم 300'),
  ('CHRYSLER', 'C300', 'سي 300'),
  ('CHRYSLER', 'PT Cruiser', 'بي تي كروزر'),
  ('CHRYSLER', 'Plymouth', 'بلايموث'),
  ('CHRYSLER', 'Crossfire', 'كروس فاير'),
  ('CHRYSLER', 'C200', 'سي 200'),
  ('CHRYSLER', 'Pacifica', 'باسيفيكا'),
  ('CHRYSLER', '300C', '300 سي'),
  ('CHRYSLER', 'Other', 'أخرى'),
  ('CITROEN', 'Regency', 'ربجنسي'),
  ('CITROEN', 'C2', 'سي 2'),
  ('CITROEN', 'C3', 'سي 3'),
  ('CITROEN', 'C1', 'سي 1'),
  ('CITROEN', 'C4', 'سي 4'),
  ('CITROEN', 'C6', 'سي 6'),
  ('CITROEN', 'Xsara', 'اكسارا'),
  ('CITROEN', 'Berlingo', 'برلنجو'),
  ('CITROEN', 'C3 Aircross', 'سي 3 إير كروس'),
  ('CITROEN', 'C4 X', 'سي 4 إكس'),
  ('CITROEN', 'C5 Aircross', 'سي 5 إير كروس'),
  ('CITROEN', 'SpaceTourer', 'سبيس تورر'),
  ('CITROEN', 'C5', 'سي 5'),
  ('CITROEN', 'Jumper', 'جمبر'),
  ('CITROEN', 'Other', 'أخرى'),
  ('Daewoo', 'Lanos', 'لانوس'),
  ('Daewoo', 'Nubira', 'نوبيرا'),
  ('Daewoo', 'Leganza', 'ليجانزا'),
  ('Daewoo', 'Mats', 'ماتز'),
  ('Daewoo', 'Other', 'أخرى'),
  ('DAIHATSU', 'Sirion', 'سيريون'),
  ('DAIHATSU', 'Terios', 'تيريوس'),
  ('DAIHATSU', 'Materia', 'ماتيريا'),
  ('DAIHATSU', 'Other', 'أخرى'),
  ('DODGE', 'Caravan', 'كارافان'),
  ('DODGE', 'Challenger', 'تشالنجر'),
  ('DODGE', 'Durango', 'دورانجو'),
  ('DODGE', 'Intrepid', 'انتربيد'),
  ('DODGE', 'Dodge Pickup', 'دودج بيك أب'),
  ('DODGE', 'RAM', 'رام'),
  ('DODGE', 'Viper', 'فايبر'),
  ('DODGE', 'Voyager', 'كارافان'),
  ('DODGE', 'Caliber', 'كاليبر'),
  ('DODGE', 'Nitro', 'نيترو'),
  ('DODGE', 'Charger', 'تشارجر'),
  ('DODGE', 'Neon', 'نيون'),
  ('DODGE', 'Ram 1500', 'آر إيه إم 1500'),
  ('DODGE', 'Other', 'أخرى'),
  ('FERRARI', 'F8 Tributo', 'إف 8 تريبوتو'),
  ('FERRARI', '488 PISTA', '488 بيستا'),
  ('FERRARI', 'GTC4Lusso', 'جي تي سي 4 لوسو'),
  ('FERRARI', 'Roma', 'روما'),
  ('FERRARI', 'MONZA', 'مونزا'),
  ('FERRARI', '812', '812'),
  ('FERRARI', 'SF90', 'إس إف 90'),
  ('FERRARI', '296 GTB', '296 جي تي بي'),
  ('FERRARI', '296 GTS', '296 جي تي إس'),
  ('FERRARI', '812 GTS', '812 جي تي إس'),
  ('FERRARI', 'F8', 'إف 8'),
  ('FERRARI', 'Purosangue', 'بوروسانجوي'),
  ('FERRARI', 'SF90 Stradale', 'إس إف 90 سترادالي'),
  ('FERRARI', '812 Superfast', '812 سوبر فاست'),
  ('FERRARI', 'Portofino M', 'بورتوفينو'),
  ('FERRARI', 'Other', 'أخرى'),
  ('FIAT', 'Fiat 500', 'فيات 500'),
  ('FIAT', 'Fiat 500X', 'فيات 500 إكس'),
  ('FIAT', 'Dolce Vita', 'دولتشي فيتا'),
  ('FIAT', 'Fiorino', 'فيورينو'),
  ('FIAT', 'Linea', 'لينيا'),
  ('FIAT', '500e', '500 إي'),
  ('FIAT', 'Doblo', 'دوبلو'),
  ('FIAT', '500 Abarth', '500 أبارث'),
  ('FIAT', 'Other', 'أخرى'),
  ('JAGUAR', 'XJ', 'إكس جيه'),
  ('JAGUAR', 'Daimler', 'ديملر'),
  ('JAGUAR', 'Sovereign', 'سوفيرجن'),
  ('JAGUAR', 'S-Type', 'إس تايب'),
  ('JAGUAR', 'X-Type', 'إكس تايب'),
  ('JAGUAR', 'XF', 'إكس إف'),
  ('JAGUAR', 'XE', 'إكس إي'),
  ('JAGUAR', 'F-Type', 'إف تايب'),
  ('JAGUAR', 'I-Pace', 'آي بيس'),
  ('JAGUAR', 'E-Pace', 'إي بيس'),
  ('JAGUAR', 'F-Pace', 'إف بيس'),
  ('JAGUAR', 'Other', 'أخرى'),
  ('LAMBORGHINI', 'Huracan', 'هوراكان'),
  ('LAMBORGHINI', 'Aventador', 'افنتادور'),
  ('LAMBORGHINI', 'Urus', 'اوروس'),
  ('LAMBORGHINI', 'Gallardo', 'غالاردو'),
  ('LAMBORGHINI', 'Aventador Ultimae', 'افنتادور ألتيمي'),
  ('LAMBORGHINI', 'Aventador SVJ', 'افنتادور إس في جيه'),
  ('LAMBORGHINI', 'Lanzador', 'لانزادور'),
  ('LAMBORGHINI', 'Revuelto', 'ريفويلتو'),
  ('LAMBORGHINI', 'Sian FKP 37', 'سيان إف كيه بي 37'),
  ('LAMBORGHINI', 'Aventador S', 'افنتادور اس'),
  ('LAMBORGHINI', 'Aventador SVJ 63', 'افنتادور إس في جيه 63'),
  ('LAMBORGHINI', 'Other', 'أخرى'),
  ('ROLLS ROYCE', 'Phantom', 'فانتوم'),
  ('ROLLS ROYCE', 'Ghost', 'قوست'),
  ('ROLLS ROYCE', 'Cullinan', 'كولينان'),
  ('ROLLS ROYCE', 'Wraith', 'ريث'),
  ('ROLLS ROYCE', 'Dawn', 'داون'),
  ('ROLLS ROYCE', 'Spectre', 'سبكتر'),
  ('ROLLS ROYCE', 'Other', 'أخرى'),
  ('PEOGEUT', '206', '206'),
  ('PEOGEUT', '307', '307'),
  ('PEOGEUT', '406', '406'),
  ('PEOGEUT', '407', '407'),
  ('PEOGEUT', '607', '607'),
  ('PEOGEUT', 'Partner', 'بارتنر'),
  ('PEOGEUT', '404', '404'),
  ('PEOGEUT', '508', '508'),
  ('PEOGEUT', 'Boxer', 'بوكسر'),
  ('PEOGEUT', '3008', '3008'),
  ('PEOGEUT', '301', '301'),
  ('PEOGEUT', '5008', '5008'),
  ('PEOGEUT', 'Expert', 'اكسبيرت'),
  ('PEOGEUT', '504', '504'),
  ('PEOGEUT', '208', '208'),
  ('PEOGEUT', '2008', '2008'),
  ('PEOGEUT', 'Landtrek', 'لاندتريك'),
  ('PEOGEUT', '408', '408'),
  ('PEOGEUT', 'Traveller', 'ترافلر'),
  ('PEOGEUT', 'Rifter', 'ريفتر'),
  ('PEOGEUT', '308', '308'),
  ('PEOGEUT', 'Other', 'أخرى'),
  ('SUBARU', 'Forester', 'فورستر'),
  ('SUBARU', 'Outback', 'اوت باك'),
  ('SUBARU', 'Impreza', 'امبريزا'),
  ('SUBARU', 'Legacy', 'ليجاسي'),
  ('SUBARU', 'WRX', 'دبليو آر إكس'),
  ('SUBARU', 'XV', 'إكس في'),
  ('SUBARU', 'WRX STI', 'دبليو آر إكس إس تي آي'),
  ('SUBARU', 'BRZ', 'بي آر زد'),
  ('SUBARU', 'Other', 'أخرى'),
  ('SUZUKI', 'Vitara', 'فيتارا'),
  ('SUZUKI', 'Samurai', 'ساموراي'),
  ('SUZUKI', 'Swift', 'سويفت'),
  ('SUZUKI', 'Jimny', 'جمني'),
  ('SUZUKI', 'Liana', 'ليانا'),
  ('SUZUKI', 'SX4', 'إس إكس 4'),
  ('SUZUKI', 'Grand Vitara', 'جراند فيتارا'),
  ('SUZUKI', 'Baleno', 'بالينو'),
  ('SUZUKI', 'Celerio', 'سيليريو'),
  ('SUZUKI', 'Ciaz', 'سياز'),
  ('SUZUKI', 'Ertiga', 'ارتيجا'),
  ('SUZUKI', 'APV Pickup', 'إيه بي في بيك اب'),
  ('SUZUKI', 'APV', 'إيه بي في فان'),
  ('SUZUKI', 'Dzire', 'ديزاير'),
  ('SUZUKI', 'Kizashi', 'كيزاشي'),
  ('SUZUKI', 'Fronx', 'فرونكس'),
  ('SUZUKI', 'Carry', 'كاري'),
  ('SUZUKI', 'Swift Sport', 'سويفت سبورت'),
  ('SUZUKI', 'Other', 'أخرى'),
  ('VOLVO', '850', '850'),
  ('VOLVO', '960', '960'),
  ('VOLVO', 'S40', 'إس 40'),
  ('VOLVO', 'S60 R', 'إس 60 آر'),
  ('VOLVO', 'S70', 'إس 70'),
  ('VOLVO', 'S80', 'إس 80'),
  ('VOLVO', 'V70 XC', 'في 70 إكس سي'),
  ('VOLVO', 'C70', 'سي 70'),
  ('VOLVO', 'XC90', 'إكس سي 90'),
  ('VOLVO', 'XC60', 'إكس سي 60'),
  ('VOLVO', 'XC40', 'إكس سي 40'),
  ('VOLVO', 'S90', 'إس 90'),
  ('VOLVO', 'S60', 'إس 60'),
  ('VOLVO', 'C40', 'سي 40'),
  ('VOLVO', 'EX30', 'إي إكس 30'),
  ('VOLVO', 'EX90', 'إي إكس 90'),
  ('VOLVO', 'Other', 'أخرى'),
  ('SKODA', 'Superb', 'سوبيرب'),
  ('SKODA', 'Rapid', 'رابيد'),
  ('SKODA', 'Octavia', 'أوكتافيا'),
  ('SKODA', 'Fabia', 'فابيا'),
  ('SKODA', 'Karoq', 'كاروك'),
  ('SKODA', 'Kodiaq', 'كودياك'),
  ('SKODA', 'Kushaq', 'كوشاك'),
  ('SKODA', 'Kamiq', 'كاميك'),
  ('SKODA', 'Scala', 'سكالا'),
  ('SKODA', 'Other', 'أخرى'),
  ('AUDI', 'A4', 'إيه 4'),
  ('AUDI', 'Q7', 'كيو 7'),
  ('AUDI', 'Q5', 'كيو 5'),
  ('AUDI', 'A3', 'إيه 3'),
  ('AUDI', 'A5', 'إيه 5'),
  ('AUDI', 'A6', 'إيه 6'),
  ('AUDI', 'A7', 'إيه 7'),
  ('AUDI', 'A8', 'إيه 8'),
  ('AUDI', 'S8', 'إس 8'),
  ('AUDI', 'TT', 'تي تي'),
  ('AUDI', 'Q3', 'كيو 3'),
  ('AUDI', 'Q8', 'كيو 8'),
  ('AUDI', 'R8', 'آر 8'),
  ('AUDI', 'RS', 'آر إس'),
  ('AUDI', 'S3', 'إس 3'),
  ('AUDI', 'S6', 'إس 6'),
  ('AUDI', 'RS7', 'آر إس 7'),
  ('AUDI', 'RS5', 'آر إس 5'),
  ('AUDI', 'S7', 'إس 7'),
  ('AUDI', 'S4', 'إس 4'),
  ('AUDI', 'e-tron', 'إي ترون'),
  ('AUDI', 'e-tron GT', 'إي-ترون جي تي'),
  ('AUDI', 'Q8 e-tron', 'كيو 8 إي-ترون'),
  ('AUDI', 'RS Q8', 'آر إس كيو 8'),
  ('AUDI', 'RS3', 'آر إس 3'),
  ('AUDI', 'SQ7', 'إس كيو 7'),
  ('AUDI', 'SQ8', 'إس كيو 8'),
  ('AUDI', 'Q6 e-tron', 'كيو 6 إي-ترون'),
  ('AUDI', 'SQ6 e-tron', 'إس كيو 6 إي-ترون'),
  ('AUDI', 'Q2', 'كيو 2'),
  ('AUDI', 'RS Q3', 'آر إس كيو 3'),
  ('AUDI', 'RS6 Avant', 'آر إس 6 أفانت'),
  ('AUDI', 'S5', 'إس 5'),
  ('AUDI', 'SQ5', 'إس كيو 5'),
  ('AUDI', 'Other', 'أخرى'),
  ('RENAULT', 'Megane', 'ميغان'),
  ('RENAULT', 'Fluence', 'فلوانس'),
  ('RENAULT', 'Safrane', 'سافران'),
  ('RENAULT', 'Clio', 'كليو'),
  ('RENAULT', 'Laguna', 'لاغونا'),
  ('RENAULT', 'Captur', 'كابتشر'),
  ('RENAULT', 'Duster', 'داستر'),
  ('RENAULT', 'Koleos', 'كوليوس'),
  ('RENAULT', 'Symbol', 'سيمبول'),
  ('RENAULT', 'Talisman', 'تاليسمان'),
  ('RENAULT', 'Dokker Van', 'دوكر فان'),
  ('RENAULT', 'Master', 'ماستر'),
  ('RENAULT', 'Megane GT', 'ميجان جي تي'),
  ('RENAULT', 'Megane RS', 'ميجان آر إس'),
  ('RENAULT', 'Express Van', 'إكسبريس فان'),
  ('RENAULT', 'Twizy', 'تويزي'),
  ('RENAULT', 'Zoe', 'زد أو إي'),
  ('RENAULT', 'Other', 'أخرى'),
  ('Buick', 'Other', 'أخرى'),
  ('Saab', 'Other', 'أخرى'),
  ('SEAT', 'Other', 'أخرى'),
  ('MG', '5', '5'),
  ('MG', '6', '6'),
  ('MG', 'ZS', 'زد إس'),
  ('MG', 'RX5', 'آر إكس 5'),
  ('MG', 'HS', 'إتش إس'),
  ('MG', 'RX8', 'آر إكس 8'),
  ('MG', 'T60', 'تي 60'),
  ('MG', 'GT', 'ام جي جي تي'),
  ('MG', 'MG 3', 'إم جي 3'),
  ('MG', 'Whale', 'ويل'),
  ('MG', 'MG 1', 'إم جي 1'),
  ('MG', 'MG 8', 'إم جي 8 بي إتش إي في'),
  ('MG', 'RX9', 'آر إكس 9'),
  ('MG', 'MG7', 'إم جي 7'),
  ('MG', '4', 'إم جي 4'),
  ('MG', 'Marvel R', 'مارفل آر'),
  ('MG', 'One', 'أو إن إي'),
  ('MG', 'Other', 'أخرى'),
  ('Proton', 'GEN•2', 'جين 2'),
  ('Proton', 'Persona', 'بيرسونا'),
  ('Proton', 'Waja', 'واجا'),
  ('Proton', 'Other', 'أخرى'),
  ('SSANGYONG', 'Musso', 'موسو'),
  ('SSANGYONG', 'Korando', 'كوراندو'),
  ('SSANGYONG', 'Actyon', 'اكتيون'),
  ('SSANGYONG', 'Rexton', 'ريكستون'),
  ('SSANGYONG', 'XLV', 'إكس إل في'),
  ('SSANGYONG', 'Tivoli', 'تيفولي'),
  ('SSANGYONG', 'Torres', 'توريس'),
  ('SSANGYONG', 'Other', 'أخرى'),
  ('CHERY', 'Quinn', 'كوين'),
  ('CHERY', 'EASTAR', 'ايستار'),
  ('CHERY', 'Chery A5', 'شيري إيه 5'),
  ('CHERY', 'Chery A3', 'شيري إيه 3'),
  ('CHERY', 'Chery A1', 'شيري إيه 1'),
  ('CHERY', 'QQ', 'كيو كيو'),
  ('CHERY', 'Arrizo 6', 'اريزو 6'),
  ('CHERY', 'Arrizo 3', 'اريزو 3'),
  ('CHERY', 'Tiggo 8', 'تيجو 8'),
  ('CHERY', 'Tiggo 7', 'تيجو 7'),
  ('CHERY', 'Tiggo 2', 'تيجو 2'),
  ('CHERY', 'Tiggo 4', 'تيجو 4'),
  ('CHERY', 'Arrizo 8', 'اريزو 8'),
  ('CHERY', 'Arrizo 5', 'اريزو 5'),
  ('CHERY', 'Tiggo 9', 'تيجو 9'),
  ('CHERY', 'Other', 'أخرى'),
  ('GEELY', 'EC8', 'إي سي 8'),
  ('GEELY', 'EC7', 'إي سي 7'),
  ('GEELY', 'LC Panda', 'باندا'),
  ('GEELY', 'Emgrand X7', 'امجراند إكس 7'),
  ('GEELY', 'Emgrand GS', 'امجراند جي إس'),
  ('GEELY', 'Emgrand 7', 'امجراند 7'),
  ('GEELY', 'Coolray', 'كولراي'),
  ('GEELY', 'Binray', 'بينراي'),
  ('GEELY', 'Azkarra', 'ازكارا'),
  ('GEELY', 'Tugella', 'توجيلا'),
  ('GEELY', 'Okavango', 'اوكافانجو'),
  ('GEELY', 'Monjaro', 'مونجارو'),
  ('GEELY', 'Starray', 'ستار راي'),
  ('GEELY', 'Preface', 'بريفيس'),
  ('GEELY', 'Geometry C', 'جيومتري'),
  ('GEELY', 'Cityray', 'سيتي راي'),
  ('GEELY', 'GX3', 'جي إكس 3 برو'),
  ('GEELY', 'Emgrand', 'إمجراند'),
  ('GEELY', 'EX5', 'إي إكس 5'),
  ('GEELY', 'GX2', 'جي إكس 2'),
  ('GEELY', 'Other', 'أخرى'),
  ('ZXAUTO', 'Grand Tiger', 'جراند تايجر'),
  ('ZXAUTO', 'Admiral', 'ادميرال'),
  ('ZXAUTO', 'Terralord', 'تيرالورد'),
  ('ZXAUTO', 'Other', 'أخرى'),
  ('GENESIS', 'G90', 'جي 90'),
  ('GENESIS', 'G80', 'جي 80'),
  ('GENESIS', 'G70', 'جي 70'),
  ('GENESIS', 'GV80', 'جي في 80'),
  ('GENESIS', 'GV70', 'جي في 70'),
  ('GENESIS', 'GV60', 'جي في 60'),
  ('GENESIS', 'Other', 'أخرى'),
  ('CHANGAN', 'Eado', 'ايدو'),
  ('CHANGAN', 'CS35', 'سي إس 35'),
  ('CHANGAN', 'CS75', 'سي إس 75'),
  ('CHANGAN', 'CS95', 'سي إس 95'),
  ('CHANGAN', 'V7', 'شانجان في 7'),
  ('CHANGAN', 'CS85', 'سي إس 85'),
  ('CHANGAN', 'Alsvin', 'السفن'),
  ('CHANGAN', 'Hunter', 'هنتر'),
  ('CHANGAN', 'UNI-T', 'يوني تي'),
  ('CHANGAN', 'UNI-K', 'يوني كي'),
  ('CHANGAN', 'UNI-V', 'يوني في'),
  ('CHANGAN', 'UNI-S', 'يوني اس'),
  ('CHANGAN', 'CS55', 'سي إس 55'),
  ('CHANGAN', 'Other', 'أخرى'),
  ('HAVAL', 'H2', 'هافال إتش 2'),
  ('HAVAL', 'H6', 'هافال إتش 6'),
  ('HAVAL', 'H9', 'هافال إتش 9'),
  ('HAVAL', 'Jolion', 'جوليان'),
  ('HAVAL', 'Dargo', 'دارجو'),
  ('HAVAL', 'H6 GT', 'إتش 6 جي تي'),
  ('HAVAL', 'H7', 'إتش 7'),
  ('HAVAL', 'V7', 'في 7'),
  ('HAVAL', 'Other', 'أخرى'),
  ('GAC', 'GA3', 'جي إيه 3'),
  ('GAC', 'GA4', 'جي إيه 4'),
  ('GAC', 'GA8', 'جي إيه 8'),
  ('GAC', 'GS3', 'جي إس 3'),
  ('GAC', 'GS4', 'جي إس 4'),
  ('GAC', 'GS8', 'جي إس 8'),
  ('GAC', 'GS5', 'جي إس 5'),
  ('GAC', 'GN6', 'جي إن 6'),
  ('GAC', 'GN8', 'جي إن 8'),
  ('GAC', 'GA6', 'جي إيه 6'),
  ('GAC', 'EMPOW', 'امباو'),
  ('GAC', 'EMZOOM', 'ام زوم'),
  ('GAC', 'EMKOO', 'امكو'),
  ('GAC', 'GE3', 'جي إي 3'),
  ('GAC', 'M8', 'إم 8'),
  ('GAC', 'Hyptec HT', 'هايبتك إتش تي'),
  ('GAC', 'Other', 'أخرى'),
  ('TANK, GREAT WALL', 'Wingle 5', 'ونجل 5'),
  ('TANK, GREAT WALL', 'Wingle 6', 'ونجل 6'),
  ('TANK, GREAT WALL', 'Wingle 7', 'ونجل 7'),
  ('TANK, GREAT WALL', 'POER', 'باور'),
  ('TANK, GREAT WALL', 'King Kong', 'كينج كونج'),
  ('TANK, GREAT WALL', 'Wingle', 'ونجل'),
  ('TANK, GREAT WALL', 'Other', 'أخرى'),
  ('FAW', 'Besturn X80', 'بسترن إكس 80'),
  ('FAW', 'Besturn B70', 'بسترن بي 70'),
  ('FAW', 'Besturn B50', 'بسترن بي 50'),
  ('FAW', 'Oley', 'أولي'),
  ('FAW', 'V80', 'في 80'),
  ('FAW', 'T80', 'تي 80'),
  ('FAW', 'T77', 'تي 77'),
  ('FAW', 'X40', 'إكس 40'),
  ('FAW', 'T33', 'تي 33'),
  ('FAW', 'T99', 'تي 99'),
  ('FAW', 'T90', 'تي 90'),
  ('FAW', 'B70S', 'بي 70 إس'),
  ('FAW', 'Other', 'أخرى'),
  ('JETOUR', 'X70', 'إكس 70'),
  ('JETOUR', 'X70s', 'إكس 70 إس'),
  ('JETOUR', 'X90', 'إكس 90'),
  ('JETOUR', 'Dashing', 'داشينج'),
  ('JETOUR', 'T2', 'تي 2'),
  ('JETOUR', 'T1', 'تي 1'),
  ('JETOUR', 'X50', 'إكس 50'),
  ('JETOUR', 'G700', 'جي 700'),
  ('JETOUR', 'X95', 'إكس 95'),
  ('JETOUR', 'Other', 'أخرى'),
  ('ALFA ROMEO', 'Giulietta', 'جوليتا'),
  ('ALFA ROMEO', 'Giulia', 'جوليا'),
  ('ALFA ROMEO', 'Stelvio', 'ستلفيو'),
  ('ALFA ROMEO', 'Tonale', 'تونالي'),
  ('ALFA ROMEO', 'Other', 'أخرى'),
  ('TATA', 'Xenon', 'زينون'),
  ('TATA', 'Other', 'أخرى'),
  ('Lifan', 'Other', 'أخرى'),
  ('Foton', 'Tunland', 'تونلاند'),
  ('Foton', 'View', 'فيو'),
  ('Foton', 'Other', 'أخرى'),
  ('JMC', 'Co-Star', 'كو-ستار'),
  ('JMC', 'Conquer 3815', 'كونكيور 3815'),
  ('JMC', 'Carrying Plus 3360', 'كارينج بلس 3360'),
  ('JMC', 'Carrying Plus 2800', 'كارينج بلس 2800'),
  ('JMC', 'Grand Avenue', 'جراند أفينيو'),
  ('JMC', 'Vigus', 'فيجس'),
  ('JMC', 'Other', 'أخرى'),
  ('MAXUS', 'D90', 'دي 90'),
  ('MAXUS', 'D60', 'دي 60'),
  ('MAXUS', '60 Tornado', '60 تورنيدو'),
  ('MAXUS', 'G10', 'جي 10'),
  ('MAXUS', 'G50', 'جي 50'),
  ('MAXUS', 'V90', 'في 90'),
  ('MAXUS', 'T70', 'تي 70'),
  ('MAXUS', 'Maxus V80', 'ماكسيس في 80'),
  ('MAXUS', 'T60', 'ماكسيس تي 60'),
  ('MAXUS', 'G90', 'ماكسيس جي 90'),
  ('MAXUS', 'T90', 'ماكسيس تي 90'),
  ('MAXUS', 'Other', 'أخرى'),
  ('VICTORY AUTO', 'Other', 'أخرى'),
  ('MCLAREN', '750S', '750 إس'),
  ('MCLAREN', '765LT', '765 إل تي'),
  ('MCLAREN', 'Artura', 'أرتورا'),
  ('MCLAREN', 'GT', 'جي تي'),
  ('MCLAREN', 'Senna', 'سينا'),
  ('MCLAREN', 'Speedtail', 'سبيدتيل'),
  ('MCLAREN', '720S', '720 إس'),
  ('MCLAREN', '570S', '570 إس'),
  ('MCLAREN', 'Other', 'أخرى'),
  ('CMC', 'Other', 'أخرى'),
  ('BYD', 'F3', 'إف 3'),
  ('BYD', 'F5', 'إف 5'),
  ('BYD', 'F7', 'إف 7'),
  ('BYD', 'S6', 'إس 6'),
  ('BYD', 'S7', 'إس 7'),
  ('BYD', 'Song', 'سونج'),
  ('BYD', 'Seal', 'سيل'),
  ('BYD', 'Atto 3', 'اتو 3'),
  ('BYD', 'Qin', 'تشين'),
  ('BYD', 'Han', 'هان'),
  ('BYD', 'Seal 7', 'سي ليون 7'),
  ('BYD', 'Shark 6', 'شارك 6'),
  ('BYD', 'Atto 8', 'اتو 8'),
  ('BYD', 'Tang', 'تانج'),
  ('BYD', 'Ti 7', 'تي آي 7'),
  ('BYD', 'Yuan', 'يوان'),
  ('BYD', 'Yaun Up', 'يوان أب'),
  ('BYD', 'Other', 'أخرى'),
  ('JAC', 'Sunray', 'صن راي'),
  ('JAC', 'N-Series', 'سلسلة إن'),
  ('JAC', 'E30X', 'إي 30 إكس'),
  ('JAC', 'J7', 'جيه 7'),
  ('JAC', 'JS4', 'جيه إس 4'),
  ('JAC', 'JS6', 'جيه إس 6'),
  ('JAC', 'M4', 'إم 4'),
  ('JAC', 'S7', 'إس 7'),
  ('JAC', 'T8', 'تي 8'),
  ('JAC', 'S3', 'إس 3'),
  ('JAC', 'J4', 'جيه 4'),
  ('JAC', 'Other', 'أخرى'),
  ('BAIC', 'D50', 'دي 50'),
  ('BAIC', 'X35', 'إكس 35'),
  ('BAIC', 'X7', 'إكس 7'),
  ('BAIC', 'BJ80', 'بي جيه 80'),
  ('BAIC', 'BJ40 C', 'بي جيه 40 سي'),
  ('BAIC', 'BJ40 SE', 'بي جيه 40 إس إي'),
  ('BAIC', 'BJ40F', 'بي جيه 40 إف'),
  ('BAIC', 'BJ40S', 'بي جيه 40 إس'),
  ('BAIC', 'BJ30', 'بي جيه 30'),
  ('BAIC', 'F40', 'إف 40'),
  ('BAIC', 'U5', 'يو 5'),
  ('BAIC', 'X55', 'إكس 55'),
  ('BAIC', 'BJ40', 'بي جيه 40'),
  ('BAIC', 'Other', 'أخرى'),
  ('Soueast', 'S09', 'إس 09'),
  ('Soueast', 'S07', 'إس 07'),
  ('Soueast', 'S06', 'إس 06'),
  ('Soueast', '06', '06'),
  ('Soueast', 'Other', 'أخرى'),
  ('Tesla', 'Model 3', 'موديل 3'),
  ('Tesla', 'Model Y', 'موديل واي'),
  ('Tesla', 'Cybertruck', 'سايبر ترك'),
  ('Tesla', 'Model S', 'موديل اس'),
  ('Tesla', 'Model X', 'موديل اكس'),
  ('Tesla', 'Other', 'أخرى'),
  ('Mahindra', 'Scorpio Pickup', 'سكوربيو بيك أب'),
  ('Mahindra', 'XUV500', 'إكس يو في 500'),
  ('Mahindra', 'Other', 'أخرى'),
  ('HONGQI', 'H5', 'إتش 5'),
  ('HONGQI', 'Ousado', 'اوسادو'),
  ('HONGQI', 'H9', 'إتش 9'),
  ('HONGQI', 'HS3', 'إتش إس 3'),
  ('HONGQI', 'HS5', 'إتش إس 5'),
  ('HONGQI', 'E-HS9', 'إي إتش إس 9'),
  ('HONGQI', 'E-HS3', 'إي إتش إس 3'),
  ('HONGQI', 'E-QM5', 'إي كيو إم 5'),
  ('HONGQI', 'H7', 'إتش 7'),
  ('HONGQI', 'HS7', 'إتش إس 7'),
  ('HONGQI', 'L5', 'إل 5'),
  ('HONGQI', 'Other', 'أخرى'),
  ('Zotye', 'E200', 'إي 200'),
  ('Zotye', 'T300', 'تي 300'),
  ('Zotye', 'T600 Sport', 'تي 600 سبورت'),
  ('Zotye', 'T700', 'تي 700'),
  ('Zotye', 'Other', 'أخرى'),
  ('Dongfeng', 'A30', 'إيه 30'),
  ('Dongfeng', 'AX7', 'إيه إكس 7'),
  ('Dongfeng', 'AX7 Mache', 'إيه إكس 7 ماخ'),
  ('Dongfeng', 'A60', 'إيه 60 ماكس'),
  ('Dongfeng', 'C31', 'سي 31'),
  ('Dongfeng', 'C35', 'سي 35'),
  ('Dongfeng', 'C32', 'سي 32'),
  ('Dongfeng', 'E32', 'إي 32'),
  ('Dongfeng', 'Forthing T5 EVO', 'فورثينج تي 5 إيفو'),
  ('Dongfeng', '007', '007'),
  ('Dongfeng', 'Shine', 'شاين'),
  ('Dongfeng', 'Mage', 'ميج'),
  ('Dongfeng', 'Huge', 'هيوج'),
  ('Dongfeng', 'AX4', 'إيه إكس 4'),
  ('Dongfeng', 'Other', 'أخرى'),
  ('Exceed', 'VX', 'في إكس'),
  ('Exceed', 'TXL', 'تي إكس إل'),
  ('Exceed', 'LX', 'اكسيد إل إكس'),
  ('Exceed', 'ES', 'إي إس'),
  ('Exceed', 'ET', 'إي تي'),
  ('Exceed', 'RX', 'آر إكس'),
  ('Exceed', 'Other', 'أخرى'),
  ('smart', 'Other', 'أخرى'),
  ('TANK, GREAT WALL', 'Tank 300', 'تانك 300'),
  ('TANK, GREAT WALL', 'Tank 500', 'تانك 500'),
  ('TANK, GREAT WALL', 'Tank 700', 'تانك 700'),
  ('Lynk&CO', '01', '01'),
  ('Lynk&CO', '03', '03'),
  ('Lynk&CO', '05', '05'),
  ('Lynk&CO', '09', '09'),
  ('Lynk&CO', '06', '06'),
  ('Lynk&CO', '900', '900'),
  ('Lynk&CO', 'Other', 'أخرى'),
  ('LUCID', 'Gravity', 'جرافيتي'),
  ('LUCID', 'Air', 'اير'),
  ('LUCID', 'Other', 'أخرى'),
  ('INEOS', 'Grenadier Station Wagen', 'جرينادير'),
  ('INEOS', 'Grenadier QuarterMaster', 'جراندير كوارتر ماستر'),
  ('INEOS', 'Other', 'أخرى'),
  ('Lotus', 'Evora', 'إيفورا'),
  ('Lotus', 'Exige', 'إكسيج'),
  ('Lotus', 'Eletre', 'إليتر'),
  ('Lotus', 'Emeya', 'إيميا'),
  ('Lotus', 'Emira', 'إميرا'),
  ('Lotus', 'Evija', 'افايا'),
  ('Lotus', 'Other', 'أخرى'),
  ('Huanghai', 'Other', 'أخرى'),
  ('Jaecoo', 'J5', 'جيه 5'),
  ('Jaecoo', 'J7', 'جيه 7'),
  ('Jaecoo', 'J8', 'جيه 8'),
  ('Jaecoo', 'Other', 'أخرى'),
  ('OMODA', 'C5', 'سي 5'),
  ('OMODA', 'Other', 'أخرى'),
  ('ROX', 'ROX 01', 'روكس 01'),
  ('ROX', 'ROX Adamas', 'روكس أداماس'),
  ('ROX', 'Other', 'أخرى'),
  ('KAIYI', 'X3', 'إكس 3'),
  ('KAIYI', 'E5', 'إي 5'),
  ('KAIYI', 'X7', 'إكس 7'),
  ('KAIYI', 'Other', 'أخرى'),
  ('BUGATTI', 'Centodieci', 'سينتوديشي'),
  ('BUGATTI', 'Chiron', 'شيرون'),
  ('BUGATTI', 'Other', 'أخرى'),
  ('Borgward', 'BX7 TS', 'بي إكس 7 تي إس'),
  ('Borgward', 'BX5', 'بي إكس 5'),
  ('Borgward', 'BX7', 'بي إكس 7'),
  ('Borgward', 'Other', 'أخرى'),
  ('Sandstorm', 'S24', 'إس 24'),
  ('Sandstorm', 'Al Reem', 'الريم'),
  ('Sandstorm', 'Other', 'أخرى'),
  ('Dorcen', 'Domy X5', 'دومي إكس 5'),
  ('Dorcen', 'Domy X7', 'دومي إكس 7'),
  ('Dorcen', 'G60s', 'جي 60 إس'),
  ('Dorcen', 'G70s', 'جي 70 إس'),
  ('Dorcen', 'Other', 'أخرى'),
  ('Ashok Leyland', 'Falcon', 'فالكون'),
  ('Ashok Leyland', 'Oyster', 'أويستر'),
  ('Ashok Leyland', 'Gazl', 'غزل'),
  ('Ashok Leyland', 'Other', 'أخرى'),
  ('Al Damani', 'DMV 300', 'دي إم في 300'),
  ('Al Damani', 'Other', 'أخرى'),
  ('Seres', 'Seres 5', 'سيريس 5'),
  ('Seres', 'Seres 7', 'سيريس 7'),
  ('Seres', 'Other', 'أخرى'),
  ('Avatr', 'Avatr 11', 'أفاتر 11'),
  ('Avatr', 'Avatr 12', 'أفاتر 12'),
  ('Avatr', 'Other', 'أخرى'),
  ('Riddara', 'RD6', 'آر دي 6'),
  ('Riddara', 'Other', 'أخرى'),
  ('MHERO', 'MHERO 1', 'إم هيرو 1'),
  ('MHERO', 'MHERO 2', 'إم هيرو 2'),
  ('MHERO', 'Other', 'أخرى'),
  ('IM Motors', 'LS7', 'إل إس 7'),
  ('IM Motors', 'Other', 'أخرى'),
  ('Denza', 'B5', 'بي 5'),
  ('Denza', 'B8', 'بي 8'),
  ('Denza', 'Other', 'أخرى'),
  ('BESTUNE', 'B70S', 'بي 70 إس'),
  ('BESTUNE', 'B70', 'بي 70'),
  ('BESTUNE', 'T77', 'تي 77'),
  ('BESTUNE', 'T33', 'تي 33'),
  ('BESTUNE', 'T55', 'تي 55'),
  ('BESTUNE', 'T99', 'تي 99'),
  ('BESTUNE', 'Other', 'أخرى'),
  ('ZNA', 'Rich', 'رتش'),
  ('ZNA', 'Other', 'أخرى'),
  ('Morgan', 'Plus Four', 'بلس فور'),
  ('Morgan', 'Other', 'أخرى'),
  ('DFSK', 'Fengon 600', 'فينجون 600'),
  ('DFSK', 'Other', 'أخرى'),
  ('ABARTH', '500e', '500 إي'),
  ('ABARTH', '595', '595'),
  ('ABARTH', '695', '695'),
  ('ABARTH', 'Other', 'أخرى'),
  ('Skywell', 'ET5', 'إي تي 5'),
  ('Skywell', 'Other', 'أخرى'),
  ('Yangwang', 'U8', 'يو 8'),
  ('Yangwang', 'Other', 'أخرى'),
  ('Xpeng', 'G6', 'جي 6'),
  ('Xpeng', 'GX', 'جي إكس'),
  ('Xpeng', 'P7+', 'بي 7 بلس'),
  ('Xpeng', 'Other', 'أخرى'),
  ('Cupra', 'Formentor', 'فورمنتور'),
  ('Cupra', 'Other', 'أخرى'),
  ('212', 'T01', 'تي 01'),
  ('212', 'Other', 'أخرى'),
  ('Theeb', 'X01', 'إكس 01'),
  ('Theeb', 'Other', 'أخرى'),
  ('MINI COOPER', 'SE', 'إس إي'),
  ('MINI COOPER', 'Clubman', 'كلوبمان'),
  ('MINI COOPER', 'Convertible', 'كشف'),
  ('MINI COOPER', 'Countryman', 'كنتريمان'),
  ('MINI COOPER', 'Hatch', 'هاتش'),
  ('MINI COOPER', 'Cooper', 'كوبر'),
  ('MINI COOPER', 'Cooper S', 'كوبر أس'),
  ('MINI COOPER', 'John Cooper Works', 'جون كوبر ووركس'),
  ('MINI COOPER', 'Cooper S Countryman', 'كوبر أس كونتري مان'),
  ('MINI COOPER', 'Other', 'أخرى'),
  ('RAM', '1500', '1500'),
  ('RAM', '2500', '2500'),
  ('RAM', '1500 TRX', '1500 تي آر إكس'),
  ('RAM', 'Other', 'أخرى'),
  ('Devel', 'Sixteen', 'سيكستين'),
  ('Devel', 'Sixty', 'سيكستي'),
  ('Devel', 'Other', 'أخرى'),
  ('Ariel', 'Atom', 'أتوم'),
  ('Ariel', 'Other', 'أخرى'),
  ('Force', 'Traveller', 'ترافلر'),
  ('Force', 'Other', 'أخرى'),
  ('Rabdan', 'One', 'أو إن إي'),
  ('Rabdan', 'Other', 'أخرى'),
  ('ZEEKR', '001', '001'),
  ('ZEEKR', 'X', 'إكس'),
  ('ZEEKR', '7X', '7 إكس'),
  ('ZEEKR', '007', '007'),
  ('ZEEKR', '9X', '9 إكس'),
  ('ZEEKR', '009', '009'),
  ('ZEEKR', 'Other', 'أخرى'),
  ('Li Auto', 'L6', 'إل 6'),
  ('Li Auto', 'L7', 'إل 7'),
  ('Li Auto', 'L9', 'إل 9'),
  ('Li Auto', 'Mega', 'ميجا'),
  ('Li Auto', 'Other', 'أخرى'),
  ('Voyah', 'Free', 'فري'),
  ('Voyah', 'Dream', 'دريم'),
  ('Voyah', 'Other', 'أخرى'),
  ('JIDU', 'Robo-01', 'روبو 01'),
  ('JIDU', 'Other', 'أخرى'),
  ('Deepal', 'S07', 'إس 07'),
  ('Deepal', 'S05', 'إس 05'),
  ('Deepal', 'Other', 'أخرى'),
  ('Alpine', 'A110', 'إيه 110'),
  ('Alpine', 'Other', 'أخرى'),
  ('Freelander', '8', '8'),
  ('Freelander', 'Other', 'أخرى'),
  ('King Long', 'Panel Van', 'بانيل فان'),
  ('King Long', 'Other', 'أخرى'),
  ('Zarooq Motors', 'SandRacer 500GT', 'ساند ريسر 500 جي تي'),
  ('Zarooq Motors', 'Other', 'أخرى'),
  ('W Motors', 'Fenyr SuperSport', 'فينير سوبر سبورت'),
  ('W Motors', 'Lykan HyperSport', 'لايكن هايبر سبورت'),
  ('W Motors', 'Other', 'أخرى'),
  ('Polestar', 'Polestar 2', 'بولستار 2'),
  ('Polestar', 'Polestar 3', 'بولستار 3'),
  ('Polestar', 'Polestar 4', 'بولستار 4'),
  ('Polestar', 'Other', 'أخرى'),
  ('Forthing', 'Friday', 'فرايداي كهربائية'),
  ('Forthing', 'S7', 'إس 7'),
  ('Forthing', 'T5 Evo', 'تي 5 إيفو'),
  ('Forthing', 'U-Tour', 'يو تور'),
  ('Forthing', 'V9', 'في 9'),
  ('Forthing', 'Other', 'أخرى'),
  ('NIO', 'ET9', 'إي تي 9'),
  ('NIO', 'EL8', 'إي إل 8'),
  ('NIO', 'ET7', 'إي تي 7'),
  ('NIO', 'Other', 'أخرى'),
  ('VGV', 'U70', 'يو 70'),
  ('VGV', 'Other', 'أخرى'),
  ('AITO', 'AITO 9', 'إم 9'),
  ('AITO', 'Other', 'أخرى'),
  ('VinFast', 'VF 8', 'في إف 8'),
  ('VinFast', 'Other', 'أخرى'),
  ('Xiaomi Auto', 'SU7', 'إس يو 7'),
  ('Xiaomi Auto', 'Other', 'أخرى'),
  ('Roewe', 'D5X', 'دي 5 إكس'),
  ('Roewe', 'D7', 'دي 7'),
  ('Roewe', 'Other', 'أخرى'),
  ('iCAUR', '03T', '03 تي'),
  ('iCAUR', 'V27', 'في 27'),
  ('iCAUR', 'Other', 'أخرى'),
  ('Brilliance', 'Other', 'أخرى'),
  ('Other', 'Other', 'أخرى'),
  ('Parts & Accessories', 'Rounds', 'جنوط'),
  ('Parts & Accessories', 'Registered', 'مسجل'),
  ('Parts & Accessories', 'Monitor', 'شاشه'),
  ('Parts & Accessories', 'Spare parts', 'قطع غيار'),
  ('Parts & Accessories', 'Other', 'أخرى'),
  ('Trucks and heavy equipment', 'Caravan', 'كارافان'),
  ('Trucks and heavy equipment', 'Volvo Trucks', 'شاحنة فولفو'),
  ('Trucks and heavy equipment', 'Mercedes Truck', 'شاحنة مرسيدس'),
  ('Trucks and heavy equipment', 'MAN Truck', 'شاحنة مان'),
  ('Trucks and heavy equipment', 'Scania Trucks', 'شاحنة سكانيا'),
  ('Trucks and heavy equipment', 'Bulldozer', 'بلدوزر'),
  ('Trucks and heavy equipment', 'Car Carrier', 'سطحه'),
  ('Trucks and heavy equipment', 'Shiol', 'شيول'),
  ('Trucks and heavy equipment', 'Tipper', 'قلاب'),
  ('Trucks and heavy equipment', 'Crane', 'رافعة'),
  ('Trucks and heavy equipment', 'Crusher', 'كسارة'),
  ('Trucks and heavy equipment', 'Agricultural equipment', 'معدات زراعية'),
  ('Trucks and heavy equipment', 'Heavy Equipment', 'معدات ثقيلة'),
  ('Trucks and heavy equipment', 'Poclain', 'بوكلين'),
  ('Trucks and heavy equipment', 'Hino Truck', 'شاحنة هينو'),
  ('Trucks and heavy equipment', 'Food Truck', 'فود ترك'),
  ('Trucks and heavy equipment', 'Other', 'أخرى'),
  ('Motorcycles', 'Honda Motorcycles', 'دباب هوندا'),
  ('Motorcycles', 'Suzuki', 'دباب سوزوكي'),
  ('Motorcycles', 'Kuzaki Motorcycles', 'دباب كوزاكي'),
  ('Motorcycles', 'Harley Motorcycles', 'دباب هارلي'),
  ('Motorcycles', 'Yamaha Motorcycles', 'دباب ياماها'),
  ('Motorcycles', 'Chinese Motorcycle', 'دباب صيني'),
  ('Motorcycles', 'Jet Ski', 'دباب بحري'),
  ('Motorcycles', 'Ram\''s Motorcycles', 'دباب رام'),
  ('Motorcycles', 'BMW Motorcycle', 'دباب بي إم دبليو'),
  ('Motorcycles', 'KTM Motorcycles', 'دباب كيه تي إم'),
  ('Motorcycles', 'Buggy Car', 'دباب بقي'),
  ('Motorcycles', 'Polaris Bike', 'دباب بولاريس'),
  ('Motorcycles', 'can am', 'دباب كانام'),
  ('Motorcycles', 'indian Motorcycle', 'دباب انديان'),
  ('Motorcycles', 'Karting', 'كارتنج'),
  ('Motorcycles', 'Haojue Motorcycle', 'دباب هاوجو'),
  ('Motorcycles', 'Ducati', 'دباب دوكاتي'),
  ('Motorcycles', 'CFMOTO', 'دباب سي اف موتو'),
  ('Motorcycles', 'Other', 'أخرى')
  ) AS v(brand_name, model_en, model_ar)
  JOIN LATERAL (
    SELECT ld.list_data_id
      FROM qvm_new_apps.list_data ld
      JOIN qvm_new_apps.lists l ON l.list_id = ld.list_id AND l.list_name = 'car_brand'
     WHERE lower(btrim(ld.list_data)) = lower(v.brand_name)
     ORDER BY ld.list_data_id
     LIMIT 1
  ) b ON true
ON CONFLICT (brand_id, lower(name_en)) DO NOTHING;

-- ── Reading ───────────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION qvm_new_apps.list_vehicle_models(p_brand_id bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SECURITY DEFINER
 SET search_path TO 'qvm_new_apps', 'public'
AS $function$
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'model_id', m.model_id, 'brand_id', m.brand_id, 'name_en', m.name_en, 'name_ar', m.name_ar)
           ORDER BY m.name_en), '[]'::jsonb)
    FROM qvm_new_apps.vehicle_models m
   WHERE m.brand_id = p_brand_id AND m.is_active;
$function$;
CREATE OR REPLACE FUNCTION public.list_vehicle_models(p_brand_id bigint)
 RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path TO 'qvm_new_apps', 'public'
AS $$ SELECT qvm_new_apps.list_vehicle_models(p_brand_id); $$;
REVOKE ALL ON FUNCTION public.list_vehicle_models(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.list_vehicle_models(bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION qvm_new_apps.list_vehicle_models(bigint) TO anon, authenticated, service_role;
